export const fulltextPayload = {
  etablissement: [
    {
      activite_principale: "6420Z",
      activite_principale_entreprise: "6420Z",
      activite_principale_entreprise_esa: null,
      activite_principale_registre_metier: null,
      arrondissement: "1",
      canton: null,
      caractere_auxiliaire: null,
      caractere_productif: null,
      caractere_productif_entreprise: null,
      categorie_entreprise: "PME",
      cedex: null,
      civilite: null,
      code_postal: "75004",
      commune: "104",
      created_at: "2019-09-01T04:00:35.000Z",
      date_creation: "20190102",
      date_creation_entreprise: "201405",
      date_debut_activite: "20190102",
      date_ess: null,
      date_introduction_base_diffusion: "201901",
      date_introduction_base_diffusion_entreprise: "201901",
      date_mise_a_jour: "2019-03-07T16:40:35",
      date_validite_activite_principale: null,
      date_validite_activite_principale_entreprise: null,
      date_validite_effectif_salarie: null,
      date_validite_effectif_salarie_entreprise: "2017",
      date_validite_rubrique_niveau_entreprise_esa: null,
      departement: "75",
      departement_commune_siege: "75104",
      departement_unite_urbaine: null,
      deuxieme_activite_secondaire_entreprise_esa: null,
      email: null,
      enseigne: null,
      etablissement_public_cooperation_intercommunale: null,
      geo_adresse: "28 Rue de Venise 75004 Paris",
      geo_id: "ADRNIVX_0000000270765963",
      geo_l4: "28 RUE DE VENISE",
      geo_l5: null,
      geo_ligne: "G",
      geo_score: "0.58",
      geo_type: "housenumber",
      id: 112277319,
      indicateur_champ_publipostage: "A",
      indicateur_mise_a_jour_1: null,
      indicateur_mise_a_jour_2: null,
      indicateur_mise_a_jour_3: null,
      indice_monoactivite_entreprise: null,
      indice_repetition: null,
      is_ess: null,
      is_saisonnier: null,
      is_siege: "1",
      l1_declaree: null,
      l1_normalisee: "CORSO BALARD",
      l2_declaree: null,
      l2_normalisee: null,
      l3_declaree: null,
      l3_normalisee: null,
      l4_declaree: "28 RUE DE VENISE",
      l4_normalisee: "28 RUE DE VENISE",
      l5_declaree: null,
      l5_normalisee: null,
      l6_declaree: "75004 PARIS 4",
      l6_normalisee: "75004 PARIS 4",
      l7_declaree: null,
      l7_normalisee: null,
      latitude: "48.861184",
      libelle_activite_principale: "Activités des sociétés holding",
      libelle_activite_principale_entreprise: "Activités des sociétés holding",
      libelle_commune: "PARIS 4E ARRONDISSEMENT",
      libelle_nature_entrepreneur_individuel: null,
      libelle_nature_juridique_entreprise:
        "Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle",
      libelle_region: null,
      libelle_tranche_effectif_salarie: null,
      libelle_tranche_effectif_salarie_entreprise: null,
      libelle_voie: "DE VENISE",
      lieu_activite: null,
      longitude: "2.350955",
      modalite_activite_principale: null,
      modalite_activite_principale_entreprise: null,
      nature_activite: null,
      nature_entrepreneur_individuel: null,
      nature_juridique_entreprise: "5720",
      nature_mise_a_jour: null,
      nic: "00035",
      nic_siege: "00035",
      nom: null,
      nom_raison_sociale: "CORSO BALARD",
      numero_rna: null,
      numero_unite_urbaine: null,
      numero_voie: "28",
      origine_creation: null,
      participation_particuliere_production: null,
      premiere_activite_secondaire_entreprise_esa: null,
      prenom: null,
      quatrieme_activite_secondaire_entreprise_esa: null,
      region: "11",
      region_siege: "11",
      sigle: null,
      siren: "802585703",
      siret: "80258570300035",
      statut_prospection: null,
      taille_unite_urbaine: null,
      tranche_chiffre_affaire_entreprise_esa: null,
      tranche_commune_detaillee: "80",
      tranche_effectif_salarie: null,
      tranche_effectif_salarie_centaine_pret: null,
      tranche_effectif_salarie_entreprise: "12",
      tranche_effectif_salarie_entreprise_centaine_pret: null,
      troisieme_activite_secondaire_entreprise_esa: null,
      type_magasin: null,
      type_voie: "RUE",
      updated_at: "2019-09-01T04:00:35.000Z",
      zone_emploi: null,
    },
    {
      activite_principale: "5610A",
      activite_principale_entreprise: "6420Z",
      activite_principale_entreprise_esa: null,
      activite_principale_registre_metier: null,
      arrondissement: "1",
      canton: null,
      caractere_auxiliaire: null,
      caractere_productif: null,
      caractere_productif_entreprise: null,
      categorie_entreprise: "PME",
      cedex: null,
      civilite: null,
      code_postal: "75015",
      commune: "115",
      created_at: "2019-09-01T03:27:10.000Z",
      date_creation: "20160801",
      date_creation_entreprise: "201405",
      date_debut_activite: "20160901",
      date_ess: null,
      date_introduction_base_diffusion: "201609",
      date_introduction_base_diffusion_entreprise: "201901",
      date_mise_a_jour: "2018-09-29T13:41:41",
      date_validite_activite_principale: null,
      date_validite_activite_principale_entreprise: null,
      date_validite_effectif_salarie: "2016",
      date_validite_effectif_salarie_entreprise: "2017",
      date_validite_rubrique_niveau_entreprise_esa: null,
      departement: "75",
      departement_commune_siege: "75104",
      departement_unite_urbaine: null,
      deuxieme_activite_secondaire_entreprise_esa: null,
      email: null,
      enseigne: null,
      etablissement_public_cooperation_intercommunale: null,
      geo_adresse: "52 Rue Balard 75015 Paris",
      geo_id: "ADRNIVX_0000000270801227",
      geo_l4: "52 RUE BALARD",
      geo_l5: null,
      geo_ligne: "G",
      geo_score: "0.56",
      geo_type: "housenumber",
      id: 108527673,
      indicateur_champ_publipostage: "A",
      indicateur_mise_a_jour_1: null,
      indicateur_mise_a_jour_2: null,
      indicateur_mise_a_jour_3: null,
      indice_monoactivite_entreprise: null,
      indice_repetition: null,
      is_ess: null,
      is_saisonnier: null,
      is_siege: "0",
      l1_declaree: null,
      l1_normalisee: "CORSO BALARD",
      l2_declaree: null,
      l2_normalisee: "52 56",
      l3_declaree: null,
      l3_normalisee: null,
      l4_declaree: "52 RUE BALARD",
      l4_normalisee: "52 RUE BALARD",
      l5_declaree: null,
      l5_normalisee: null,
      l6_declaree: "75015 PARIS 15",
      l6_normalisee: "75015 PARIS 15",
      l7_declaree: null,
      l7_normalisee: null,
      latitude: "48.84137",
      libelle_activite_principale: "Restauration traditionnelle",
      libelle_activite_principale_entreprise: "Activités des sociétés holding",
      libelle_commune: "PARIS 15E ARRONDISSEMENT",
      libelle_nature_entrepreneur_individuel: null,
      libelle_nature_juridique_entreprise:
        "Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle",
      libelle_region: null,
      libelle_tranche_effectif_salarie: null,
      libelle_tranche_effectif_salarie_entreprise: null,
      libelle_voie: "BALARD",
      lieu_activite: null,
      longitude: "2.27767",
      modalite_activite_principale: null,
      modalite_activite_principale_entreprise: null,
      nature_activite: null,
      nature_entrepreneur_individuel: null,
      nature_juridique_entreprise: "5720",
      nature_mise_a_jour: null,
      nic: "00027",
      nic_siege: "00035",
      nom: null,
      nom_raison_sociale: "CORSO BALARD",
      numero_rna: null,
      numero_unite_urbaine: null,
      numero_voie: "52",
      origine_creation: null,
      participation_particuliere_production: null,
      premiere_activite_secondaire_entreprise_esa: null,
      prenom: null,
      quatrieme_activite_secondaire_entreprise_esa: null,
      region: "11",
      region_siege: "11",
      sigle: null,
      siren: "802585703",
      siret: "80258570300027",
      statut_prospection: null,
      taille_unite_urbaine: null,
      tranche_chiffre_affaire_entreprise_esa: null,
      tranche_commune_detaillee: "80",
      tranche_effectif_salarie: "00",
      tranche_effectif_salarie_centaine_pret: null,
      tranche_effectif_salarie_entreprise: "12",
      tranche_effectif_salarie_entreprise_centaine_pret: null,
      troisieme_activite_secondaire_entreprise_esa: null,
      type_magasin: null,
      type_voie: "RUE",
      updated_at: "2019-09-01T03:27:10.000Z",
      zone_emploi: null,
    },
  ],
  page: 1,
  per_page: 10,
  spellcheck: null,
  suggestions: ["corso balard"],
  total_pages: 1,
  total_results: 2,
};

export const siretPayload = {
  etablissement: {
    activite_principale: "64.20Z",
    activite_principale_registre_metiers: null,
    annee_effectifs: null,
    caractere_employeur: "O",
    code_cedex: null,
    code_cedex_2: null,
    code_commune: "75104",
    code_commune_2: null,
    code_pays_etranger: null,
    code_pays_etranger_2: null,
    code_postal: "75004",
    code_postal_2: null,
    complement_adresse: null,
    complement_adresse_2: null,
    created_at: "2020-09-03T03:36:51.236+02:00",
    date_creation: "2019-01-02",
    date_debut: "2019-01-02",
    date_dernier_traitement: "2019-03-07T16:40:35",
    denomination_usuelle: null,
    distribution_speciale: null,
    distribution_speciale_2: null,
    enseigne_1: null,
    enseigne_2: null,
    enseigne_3: null,
    etablissement_siege: "true",
    etat_administratif: "A",
    geo_adresse: "28 Rue de Venise 75004 Paris",
    geo_id: "75104_9655_00028",
    geo_l4: "28 RUE DE VENISE",
    geo_l5: null,
    geo_ligne: "G",
    geo_score: "0.61",
    geo_type: "housenumber",
    id: 113238717,
    indice_repetition: null,
    indice_repetition_2: null,
    latitude: "48.861181",
    libelle_cedex: null,
    libelle_cedex_2: null,
    libelle_commune: "PARIS 4",
    libelle_commune_2: null,
    libelle_commune_etranger: null,
    libelle_commune_etranger_2: null,
    libelle_pays_etranger: null,
    libelle_pays_etranger_2: null,
    libelle_voie: "DE VENISE",
    libelle_voie_2: null,
    longitude: "2.350967",
    nic: "00035",
    nombre_periodes: "1",
    nomenclature_activite_principale: "NAFRev2",
    numero_voie: "28",
    numero_voie_2: null,
    siren: "802585703",
    siret: "80258570300035",
    statut_diffusion: "O",
    tranche_effectifs: null,
    type_voie: "RUE",
    type_voie_2: null,
    unite_legale: {
      activite_principale: "64.20Z",
      annee_categorie_entreprise: "2018",
      annee_effectifs: "2018",
      caractere_employeur: "O",
      categorie_entreprise: "ETI",
      categorie_juridique: "5710",
      created_at: "2020-09-02T02:51:28.319+02:00",
      date_creation: "2014-05-01",
      date_debut: "2019-01-02",
      date_dernier_traitement: "2020-08-25T11:12:31",
      date_fin: null,
      denomination: "CORSO BALARD",
      denomination_usuelle_1: null,
      denomination_usuelle_2: null,
      denomination_usuelle_3: null,
      economie_sociale_solidaire: "N",
      etablissement_siege: {
        activite_principale: "64.20Z",
        activite_principale_registre_metiers: null,
        annee_effectifs: null,
        caractere_employeur: "O",
        code_cedex: null,
        code_cedex_2: null,
        code_commune: "75104",
        code_commune_2: null,
        code_pays_etranger: null,
        code_pays_etranger_2: null,
        code_postal: "75004",
        code_postal_2: null,
        complement_adresse: null,
        complement_adresse_2: null,
        created_at: "2020-09-03T03:36:51.236+02:00",
        date_creation: "2019-01-02",
        date_debut: "2019-01-02",
        date_dernier_traitement: "2019-03-07T16:40:35",
        denomination_usuelle: null,
        distribution_speciale: null,
        distribution_speciale_2: null,
        enseigne_1: null,
        enseigne_2: null,
        enseigne_3: null,
        etablissement_siege: "true",
        etat_administratif: "A",
        geo_adresse: "28 Rue de Venise 75004 Paris",
        geo_id: "75104_9655_00028",
        geo_l4: "28 RUE DE VENISE",
        geo_l5: null,
        geo_ligne: "G",
        geo_score: "0.61",
        geo_type: "housenumber",
        id: 113238717,
        indice_repetition: null,
        indice_repetition_2: null,
        latitude: "48.861181",
        libelle_cedex: null,
        libelle_cedex_2: null,
        libelle_commune: "PARIS 4",
        libelle_commune_2: null,
        libelle_commune_etranger: null,
        libelle_commune_etranger_2: null,
        libelle_pays_etranger: null,
        libelle_pays_etranger_2: null,
        libelle_voie: "DE VENISE",
        libelle_voie_2: null,
        longitude: "2.350967",
        nic: "00035",
        nombre_periodes: "1",
        nomenclature_activite_principale: "NAFRev2",
        numero_voie: "28",
        numero_voie_2: null,
        siren: "802585703",
        siret: "80258570300035",
        statut_diffusion: "O",
        tranche_effectifs: null,
        type_voie: "RUE",
        type_voie_2: null,
        unite_legale_id: 61160747,
        updated_at: "2020-09-03T03:36:51.236+02:00",
      },
      etat_administratif: "A",
      id: 61160747,
      identifiant_association: null,
      nic_siege: "00035",
      nom: null,
      nom_usage: null,
      nombre_periodes: "4",
      nomenclature_activite_principale: "NAFRev2",
      prenom_1: null,
      prenom_2: null,
      prenom_3: null,
      prenom_4: null,
      prenom_usuel: null,
      pseudonyme: null,
      sexe: null,
      sigle: null,
      siren: "802585703",
      statut_diffusion: "O",
      tranche_effectifs: "12",
      unite_purgee: null,
      updated_at: "2020-09-02T02:51:28.319+02:00",
    },
    unite_legale_id: 61160747,
    updated_at: "2020-09-03T03:36:51.236+02:00",
  },
};

export const sirenPayload = {
  unite_legale: {
    activite_principale: "64.20Z",
    annee_categorie_entreprise: "2018",
    annee_effectifs: "2018",
    caractere_employeur: "O",
    categorie_entreprise: "ETI",
    categorie_juridique: "5710",
    created_at: "2020-09-02T02:51:28.319+02:00",
    date_creation: "2014-05-01",
    date_debut: "2019-01-02",
    date_dernier_traitement: "2020-08-25T11:12:31",
    date_fin: null,
    denomination: "CORSO BALARD",
    denomination_usuelle_1: null,
    denomination_usuelle_2: null,
    denomination_usuelle_3: null,
    economie_sociale_solidaire: "N",
    etablissement_siege: {
      activite_principale: "64.20Z",
      activite_principale_registre_metiers: null,
      annee_effectifs: null,
      caractere_employeur: "O",
      code_cedex: null,
      code_cedex_2: null,
      code_commune: "75104",
      code_commune_2: null,
      code_pays_etranger: null,
      code_pays_etranger_2: null,
      code_postal: "75004",
      code_postal_2: null,
      complement_adresse: null,
      complement_adresse_2: null,
      created_at: "2020-09-03T03:36:51.236+02:00",
      date_creation: "2019-01-02",
      date_debut: "2019-01-02",
      date_dernier_traitement: "2019-03-07T16:40:35",
      denomination_usuelle: null,
      distribution_speciale: null,
      distribution_speciale_2: null,
      enseigne_1: null,
      enseigne_2: null,
      enseigne_3: null,
      etablissement_siege: "true",
      etat_administratif: "A",
      geo_adresse: "28 Rue de Venise 75004 Paris",
      geo_id: "75104_9655_00028",
      geo_l4: "28 RUE DE VENISE",
      geo_l5: null,
      geo_ligne: "G",
      geo_score: "0.61",
      geo_type: "housenumber",
      id: 113238717,
      indice_repetition: null,
      indice_repetition_2: null,
      latitude: "48.861181",
      libelle_cedex: null,
      libelle_cedex_2: null,
      libelle_commune: "PARIS 4",
      libelle_commune_2: null,
      libelle_commune_etranger: null,
      libelle_commune_etranger_2: null,
      libelle_pays_etranger: null,
      libelle_pays_etranger_2: null,
      libelle_voie: "DE VENISE",
      libelle_voie_2: null,
      longitude: "2.350967",
      nic: "00035",
      nombre_periodes: "1",
      nomenclature_activite_principale: "NAFRev2",
      numero_voie: "28",
      numero_voie_2: null,
      siren: "802585703",
      siret: "80258570300035",
      statut_diffusion: "O",
      tranche_effectifs: null,
      type_voie: "RUE",
      type_voie_2: null,
      unite_legale_id: 61160747,
      updated_at: "2020-09-03T03:36:51.236+02:00",
    },
    etablissements: [
      {
        activite_principale: "56.10A",
        activite_principale_registre_metiers: null,
        annee_effectifs: null,
        caractere_employeur: "O",
        code_cedex: null,
        code_cedex_2: null,
        code_commune: "75115",
        code_commune_2: null,
        code_pays_etranger: null,
        code_pays_etranger_2: null,
        code_postal: "75015",
        code_postal_2: null,
        complement_adresse: "52-56",
        complement_adresse_2: null,
        created_at: "2020-09-03T03:43:30.047+02:00",
        date_creation: "2016-08-01",
        date_debut: "2016-09-01",
        date_dernier_traitement: "2018-09-29T13:41:41",
        denomination_usuelle: null,
        distribution_speciale: null,
        distribution_speciale_2: null,
        enseigne_1: null,
        enseigne_2: null,
        enseigne_3: null,
        etablissement_siege: "false",
        etat_administratif: "A",
        geo_adresse: "52 Rue Balard 75015 Paris",
        geo_id: "75115_0639_00052",
        geo_l4: "52 RUE BALARD",
        geo_l5: null,
        geo_ligne: "G",
        geo_score: "0.58",
        geo_type: "housenumber",
        id: 114711036,
        indice_repetition: null,
        indice_repetition_2: null,
        latitude: "48.841366",
        libelle_cedex: null,
        libelle_cedex_2: null,
        libelle_commune: "PARIS 15",
        libelle_commune_2: null,
        libelle_commune_etranger: null,
        libelle_commune_etranger_2: null,
        libelle_pays_etranger: null,
        libelle_pays_etranger_2: null,
        libelle_voie: "BALARD",
        libelle_voie_2: null,
        longitude: "2.277674",
        nic: "00027",
        nombre_periodes: "2",
        nomenclature_activite_principale: "NAFRev2",
        numero_voie: "52",
        numero_voie_2: null,
        siren: "802585703",
        siret: "80258570300027",
        statut_diffusion: "O",
        tranche_effectifs: "NN",
        type_voie: "RUE",
        type_voie_2: null,
        unite_legale_id: 61160747,
        updated_at: "2020-09-03T03:43:30.047+02:00",
      },
      {
        activite_principale: "64.20Z",
        activite_principale_registre_metiers: null,
        annee_effectifs: null,
        caractere_employeur: "O",
        code_cedex: null,
        code_cedex_2: null,
        code_commune: "75104",
        code_commune_2: null,
        code_pays_etranger: null,
        code_pays_etranger_2: null,
        code_postal: "75004",
        code_postal_2: null,
        complement_adresse: null,
        complement_adresse_2: null,
        created_at: "2020-09-03T03:36:51.236+02:00",
        date_creation: "2019-01-02",
        date_debut: "2019-01-02",
        date_dernier_traitement: "2019-03-07T16:40:35",
        denomination_usuelle: null,
        distribution_speciale: null,
        distribution_speciale_2: null,
        enseigne_1: null,
        enseigne_2: null,
        enseigne_3: null,
        etablissement_siege: "true",
        etat_administratif: "A",
        geo_adresse: "28 Rue de Venise 75004 Paris",
        geo_id: "75104_9655_00028",
        geo_l4: "28 RUE DE VENISE",
        geo_l5: null,
        geo_ligne: "G",
        geo_score: "0.61",
        geo_type: "housenumber",
        id: 113238717,
        indice_repetition: null,
        indice_repetition_2: null,
        latitude: "48.861181",
        libelle_cedex: null,
        libelle_cedex_2: null,
        libelle_commune: "PARIS 4",
        libelle_commune_2: null,
        libelle_commune_etranger: null,
        libelle_commune_etranger_2: null,
        libelle_pays_etranger: null,
        libelle_pays_etranger_2: null,
        libelle_voie: "DE VENISE",
        libelle_voie_2: null,
        longitude: "2.350967",
        nic: "00035",
        nombre_periodes: "1",
        nomenclature_activite_principale: "NAFRev2",
        numero_voie: "28",
        numero_voie_2: null,
        siren: "802585703",
        siret: "80258570300035",
        statut_diffusion: "O",
        tranche_effectifs: null,
        type_voie: "RUE",
        type_voie_2: null,
        unite_legale_id: 61160747,
        updated_at: "2020-09-03T03:36:51.236+02:00",
      },
      {
        activite_principale: "64.20Z",
        activite_principale_registre_metiers: null,
        annee_effectifs: "2018",
        caractere_employeur: "N",
        code_cedex: null,
        code_cedex_2: null,
        code_commune: "75102",
        code_commune_2: null,
        code_pays_etranger: null,
        code_pays_etranger_2: null,
        code_postal: "75002",
        code_postal_2: null,
        complement_adresse: null,
        complement_adresse_2: null,
        created_at: "2020-09-03T03:36:19.096+02:00",
        date_creation: "2014-05-01",
        date_debut: "2019-01-02",
        date_dernier_traitement: "2020-08-25T11:12:31",
        denomination_usuelle: null,
        distribution_speciale: null,
        distribution_speciale_2: null,
        enseigne_1: null,
        enseigne_2: null,
        enseigne_3: null,
        etablissement_siege: "false",
        etat_administratif: "F",
        geo_adresse: "28 Rue Notre-dame des Victoires 75002 Paris",
        geo_id: "75102_6840_00028",
        geo_l4: "28 RUE NOTRE DAME DES VICTOIRES",
        geo_l5: null,
        geo_ligne: "G",
        geo_score: "0.69",
        geo_type: "housenumber",
        id: 113118965,
        indice_repetition: null,
        indice_repetition_2: null,
        latitude: "48.867985",
        libelle_cedex: null,
        libelle_cedex_2: null,
        libelle_commune: "PARIS 2",
        libelle_commune_2: null,
        libelle_commune_etranger: null,
        libelle_commune_etranger_2: null,
        libelle_pays_etranger: null,
        libelle_pays_etranger_2: null,
        libelle_voie: "NOTRE DAME DES VICTOIRES",
        libelle_voie_2: null,
        longitude: "2.341772",
        nic: "00019",
        nombre_periodes: "2",
        nomenclature_activite_principale: "NAFRev2",
        numero_voie: "28",
        numero_voie_2: null,
        siren: "802585703",
        siret: "80258570300019",
        statut_diffusion: "O",
        tranche_effectifs: "12",
        type_voie: "RUE",
        type_voie_2: null,
        unite_legale_id: 61160747,
        updated_at: "2020-09-03T03:36:19.096+02:00",
      },
    ],
    etat_administratif: "A",
    id: 61160747,
    identifiant_association: null,
    nic_siege: "00035",
    nom: null,
    nom_usage: null,
    nombre_periodes: "4",
    nomenclature_activite_principale: "NAFRev2",
    prenom_1: null,
    prenom_2: null,
    prenom_3: null,
    prenom_4: null,
    prenom_usuel: null,
    pseudonyme: null,
    sexe: null,
    sigle: null,
    siren: "802585703",
    statut_diffusion: "O",
    tranche_effectifs: "12",
    unite_purgee: null,
    updated_at: "2020-09-02T02:51:28.319+02:00",
  },
};

export const siretIdccPayload = [
  {
    conventions: [
      {
        active: true,
        date_publi: "1997-12-07T00:00:00.000Z",
        effectif: 580085,
        etat: "VIGUEUR_ETEN",
        id: "KALICONT000005635534",
        mtime: 1562700340,
        nature: "IDCC",
        num: "1979",
        shortTitle: "Hôtels Cafés Restaurants (Hcr)",
        texte_de_base: "KALITEXT000005670044",
        title:
          "Convention collective nationale des hôtels, cafés restaurants (HCR) du 30 avril 1997",
        url:
          "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635534",
      },
    ],
    siret: "80258570300027",
  },
  {
    conventions: [],
    siret: "80258570300035",
  },
  {
    conventions: [],
    siret: "80258570300019",
  },
];
