FROM node:14.17-alpine3.13 as builder


WORKDIR /app

# root packages (lerna)
COPY ./package.json .
COPY ./yarn.lock .


COPY ./lerna.json .
COPY ./packages ./packages

RUN yarn --frozen-lockfile && yarn cache clean


# dont include API in frontend build
RUN rm -rf ./packages/code-du-travail-api

RUN yarn build

# FROM node:14.17-alpine3.13

# WORKDIR /app

# COPY --from=builder /app/packages/ ./

ENTRYPOINT ["yarn", "workspace", "@cdt/frontend", "start"]
