FROM node:10.8.0-alpine

COPY ./packages/code-du-travail-api/package.json /app/package.json
COPY yarn.lock /app/yarn.lock

WORKDIR /app

RUN yarn

COPY ./packages/code-du-travail-api /app

ENTRYPOINT ["yarn", "start"]
