export const searchWithNoResponse = {
  results: [],
  total_results: 0,
  page: 1,
  per_page: 25,
  total_pages: 1,
};

export const searchWithNameMockResponse = {
  results: [
    {
      siren: "313811515",
      nom_complet: "CARREFOUR BANQUE",
      nom_raison_sociale: "CARREFOUR BANQUE",
      sigle: null,
      nombre_etablissements: 210,
      nombre_etablissements_ouverts: 69,
      siege: {
        activite_principale: "64.92Z",
        activite_principale_registre_metier: null,
        annee_tranche_effectif_salarie: null,
        adresse:
          "ZAE SAINT GUENAULT 1 RUE JEAN MERMOZ 91000 EVRY-COURCOURONNES",
        caractere_employeur: "N",
        cedex: null,
        code_pays_etranger: null,
        code_postal: "91000",
        commune: "91228",
        complement_adresse: "ZAE SAINT GUENAULT",
        coordonnees: null,
        date_creation: "2022-09-22",
        date_debut_activite: "2022-09-22",
        date_fermeture: null,
        date_mise_a_jour: null,
        date_mise_a_jour_insee: "2024-05-15T05:19:02",
        departement: "91",
        distribution_speciale: null,
        epci: "200059228",
        est_siege: true,
        etat_administratif: "A",
        geo_adresse: null,
        geo_id: null,
        indice_repetition: null,
        latitude: null,
        libelle_cedex: null,
        libelle_commune: "EVRY-COURCOURONNES",
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: "JEAN MERMOZ",
        liste_enseignes: null,
        liste_finess: null,
        liste_id_bio: null,
        liste_idcc: ["0478"],
        liste_id_organisme_formation: null,
        liste_rge: null,
        liste_uai: null,
        longitude: null,
        nom_commercial: null,
        numero_voie: "1",
        region: "11",
        siret: "31381151502140",
        statut_diffusion_etablissement: "O",
        tranche_effectif_salarie: null,
        type_voie: "RUE",
      },
      activite_principale: "64.92Z",
      categorie_entreprise: "GE",
      caractere_employeur: null,
      annee_categorie_entreprise: "2021",
      date_creation: "1978-01-01",
      date_fermeture: null,
      date_mise_a_jour: "2024-06-27T08:00:24",
      date_mise_a_jour_insee: "2024-05-15T05:19:02",
      date_mise_a_jour_rne: "2024-05-22T04:01:01",
      dirigeants: [
        {
          nom: "CHAILLAN",
          prenoms: "NICOLAS",
          annee_de_naissance: "1978",
          date_de_naissance: "1978-12",
          qualite: "Directeur général délégué",
          nationalite: "Française",
          type_dirigeant: "personne physique",
        },
        {
          nom: "COURREGES",
          prenoms: "CLAIRE THERESE",
          annee_de_naissance: "1977",
          date_de_naissance: "1977-09",
          qualite: "Administrateur",
          nationalite: "Française",
          type_dirigeant: "personne physique",
        },
        {
          nom: "DOS SANTOS LEANDRO",
          prenoms: "JOAO MIGUEL",
          annee_de_naissance: "1972",
          date_de_naissance: "1972-02",
          qualite: "Président du conseil d'administration",
          nationalite: "Portugaise",
          type_dirigeant: "personne physique",
        },
        {
          nom: "DASSIÉ (FENART)",
          prenoms: "CAROLINE NELLY MARCELLE",
          annee_de_naissance: "1972",
          date_de_naissance: "1972-07",
          qualite: "Administrateur",
          nationalite: "Française",
          type_dirigeant: "personne physique",
        },
        {
          nom: "GRUNBERG (HAZAN)",
          prenoms: "ORLI",
          annee_de_naissance: "1977",
          date_de_naissance: "1977-08",
          qualite: "Directeur Général",
          nationalite: "Française",
          type_dirigeant: "personne physique",
        },
        {
          nom: "MUNCH",
          prenoms: "JULIEN",
          annee_de_naissance: "1976",
          date_de_naissance: "1976-04",
          qualite: "Administrateur",
          nationalite: "Française",
          type_dirigeant: "personne physique",
        },
        {
          nom: "VENANCIO",
          prenoms: "FILIPE OLIVEIRA",
          annee_de_naissance: "1978",
          date_de_naissance: "1978-05",
          qualite: "Directeur général délégué",
          nationalite: "Française",
          type_dirigeant: "personne physique",
        },
        {
          siren: "542097902",
          denomination: "BNP PARIBAS PERSONAL FINANCE",
          qualite: "Administrateur",
          type_dirigeant: "personne morale",
        },
        {
          siren: "572028041",
          denomination: "DELOITTE & ASSOCIES",
          qualite: "Commissaire aux comptes titulaire",
          type_dirigeant: "personne morale",
        },
        {
          siren: "784824153",
          denomination: "MAZARS",
          qualite: "Commissaire aux comptes titulaire",
          type_dirigeant: "personne morale",
        },
      ],
      etat_administratif: "A",
      nature_juridique: "5599",
      section_activite_principale: "K",
      tranche_effectif_salarie: "41",
      annee_tranche_effectif_salarie: "2021",
      statut_diffusion: "O",
      matching_etablissements: [
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "13 QUAI DE LA MARNE 51200 EPERNAY",
          caractere_employeur: "O",
          code_postal: "51200",
          commune: "51230",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "200067684",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "49.04877999999997",
          libelle_commune: "EPERNAY",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "3.963129999999999",
          nom_commercial: null,
          region: "44",
          siret: "31381151501076",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "01",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: null,
          adresse: "RUE DES PLATANES 85000 LA ROCHE-SUR-YON",
          caractere_employeur: "O",
          code_postal: "85000",
          commune: "85191",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "248500589",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "46.66494799999998",
          libelle_commune: "LA ROCHE-SUR-YON",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "-1.4514039999999986",
          nom_commercial: null,
          region: "52",
          siret: "31381151501142",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: null,
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "CENTRE COMMERCIAL RTE DE MAILLOT 89100 SENS",
          caractere_employeur: "O",
          code_postal: "89100",
          commune: "89387",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "248900334",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: null,
          libelle_commune: "SENS",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: null,
          nom_commercial: null,
          region: "27",
          siret: "31381151501159",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "NN",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "ROUTE DE VOULX 89100 SENS",
          caractere_employeur: "O",
          code_postal: "89100",
          commune: "89387",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "248900334",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "48.19828499999998",
          libelle_commune: "SENS",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "3.264756999999999",
          nom_commercial: null,
          region: "27",
          siret: "31381151501167",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "NN",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "280 AVENUE GABRIEL PERI 78360 MONTESSON",
          caractere_employeur: "O",
          code_postal: "78360",
          commune: "78418",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "200058519",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "48.928529999999995",
          libelle_commune: "MONTESSON",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ["0478"],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "2.1445259999999995",
          nom_commercial: null,
          region: "11",
          siret: "31381151501175",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "03",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse:
            "CENTRE COMMERCIAL REGIONAL SQ DU GERME DE VILLE 78180 MONTIGNY LE BRETONNEUX",
          caractere_employeur: "O",
          code_postal: "78180",
          commune: "78423",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-12-26",
          date_fermeture: null,
          epci: "200058782",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: null,
          libelle_commune: "MONTIGNY LE BRETONNEUX",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ["0478"],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: null,
          nom_commercial: null,
          region: "11",
          siret: "31381151501209",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "03",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "AVENUE DU GRAND COTTIGNIES 59290 WASQUEHAL",
          caractere_employeur: "O",
          code_postal: "59290",
          commune: "59646",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "200093201",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "50.683181999999995",
          libelle_commune: "WASQUEHAL",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ["0478"],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "3.131284000000001",
          nom_commercial: null,
          region: "32",
          siret: "31381151501258",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "03",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "180 AVENUE FRANCOIS MITTERRAND 91200 ATHIS-MONS",
          caractere_employeur: "O",
          code_postal: "91200",
          commune: "91027",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "200054781",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "48.712094999999984",
          libelle_commune: "ATHIS-MONS",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ["0478"],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "2.371372000000001",
          nom_commercial: null,
          region: "11",
          siret: "31381151501274",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "03",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "RTE NATIONALE 13 78240 CHAMBOURCY",
          caractere_employeur: "O",
          code_postal: "78240",
          commune: "78133",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-12-26",
          date_fermeture: null,
          epci: "200058519",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: null,
          libelle_commune: "CHAMBOURCY",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ["0478"],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: null,
          nom_commercial: null,
          region: "11",
          siret: "31381151501308",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "03",
        },
        {
          activite_principale: "64.92Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "CTRE CIAL DE LA CREULE LA CREULE 59190 HAZEBROUCK",
          caractere_employeur: "O",
          code_postal: "59190",
          commune: "59295",
          date_creation: "2010-04-30",
          date_debut_activite: "2010-04-30",
          date_fermeture: null,
          epci: "200040947",
          est_siege: false,
          etat_administratif: "A",
          geo_id: null,
          latitude: "50.74141899999998",
          libelle_commune: "HAZEBROUCK",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "2.5499320000000005",
          nom_commercial: null,
          region: "32",
          siret: "31381151501324",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "01",
        },
      ],
      finances: {
        "2022": {
          ca: 0,
          resultat_net: 32608000,
        },
      },
      complements: {
        collectivite_territoriale: null,
        convention_collective_renseignee: true,
        liste_idcc: ["0478", "2120"],
        egapro_renseignee: true,
        est_association: false,
        est_bio: false,
        est_entrepreneur_individuel: false,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_organisme_formation: false,
        est_qualiopi: false,
        liste_id_organisme_formation: null,
        est_rge: false,
        est_service_public: false,
        est_siae: false,
        est_societe_mission: false,
        est_uai: false,
        identifiant_association: null,
        statut_entrepreneur_spectacle: null,
        type_siae: null,
      },
    },
  ],
  total_results: 1,
  page: 1,
  per_page: 25,
  total_pages: 1,
};

export const searchWithOnePostalCodeMockResponse = {
  results: [
    {
      siren: "429904436",
      nom_complet: "JEREMIE BOUILLON",
      nom_raison_sociale: null,
      sigle: null,
      nombre_etablissements: 1,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: "90.03A",
        activite_principale_registre_metier: null,
        annee_tranche_effectif_salarie: null,
        adresse: "BAT A - 5EME ETAGE 4 IMPASSE MOLIN 75018 PARIS",
        caractere_employeur: "N",
        cedex: null,
        code_pays_etranger: null,
        code_postal: "75018",
        commune: "75118",
        complement_adresse: "BAT A - 5EME ETAGE",
        coordonnees: "48.890519999999974,2.3643779999999994",
        date_creation: "2011-09-01",
        date_debut_activite: "2011-09-01",
        date_fermeture: null,
        date_mise_a_jour: null,
        date_mise_a_jour_insee: "2024-03-30T07:27:46",
        departement: "75",
        distribution_speciale: null,
        epci: "200054781",
        est_siege: true,
        etat_administratif: "A",
        geo_adresse: null,
        geo_id: null,
        indice_repetition: null,
        latitude: "48.890519999999974",
        libelle_cedex: null,
        libelle_commune: "PARIS",
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: "MOLIN",
        liste_enseignes: null,
        liste_finess: null,
        liste_id_bio: null,
        liste_idcc: null,
        liste_id_organisme_formation: null,
        liste_rge: null,
        liste_uai: null,
        longitude: "2.3643779999999994",
        nom_commercial: null,
        numero_voie: "4",
        region: "11",
        siret: "42990443600020",
        statut_diffusion_etablissement: "O",
        tranche_effectif_salarie: null,
        type_voie: "IMPASSE",
      },
      activite_principale: "90.03A",
      categorie_entreprise: "PME",
      caractere_employeur: null,
      annee_categorie_entreprise: "2021",
      date_creation: "1999-12-06",
      date_fermeture: null,
      date_mise_a_jour: "2024-06-27T08:59:27",
      date_mise_a_jour_insee: "2024-03-22T14:26:06",
      date_mise_a_jour_rne: "2024-01-13T03:28:57",
      dirigeants: [
        {
          nom: "BOUILLON",
          prenoms: "JEREMIE",
          annee_de_naissance: null,
          date_de_naissance: null,
          qualite: null,
          nationalite: null,
          type_dirigeant: "personne physique",
        },
      ],
      etat_administratif: "A",
      nature_juridique: "1000",
      section_activite_principale: "R",
      tranche_effectif_salarie: null,
      annee_tranche_effectif_salarie: null,
      statut_diffusion: "O",
      matching_etablissements: [
        {
          activite_principale: "90.03A",
          annee_tranche_effectif_salarie: null,
          adresse: "BAT A - 5EME ETAGE 4 IMPASSE MOLIN 75018 PARIS",
          caractere_employeur: "N",
          code_postal: "75018",
          commune: "75118",
          date_creation: "2011-09-01",
          date_debut_activite: "2011-09-01",
          date_fermeture: null,
          epci: "200054781",
          est_siege: true,
          etat_administratif: "A",
          geo_id: null,
          latitude: "48.890519999999974",
          libelle_commune: "PARIS",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "2.3643779999999994",
          nom_commercial: null,
          region: "11",
          siret: "42990443600020",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: null,
        },
      ],
      finances: {},
      complements: {
        collectivite_territoriale: null,
        convention_collective_renseignee: false,
        liste_idcc: null,
        egapro_renseignee: false,
        est_association: false,
        est_bio: false,
        est_entrepreneur_individuel: true,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_organisme_formation: false,
        est_qualiopi: false,
        liste_id_organisme_formation: null,
        est_rge: false,
        est_service_public: false,
        est_siae: false,
        est_societe_mission: false,
        est_uai: false,
        identifiant_association: null,
        statut_entrepreneur_spectacle: null,
        type_siae: null,
      },
    },
    {
      siren: "893208595",
      nom_complet: "LEO BOUILLON",
      nom_raison_sociale: null,
      sigle: null,
      nombre_etablissements: 1,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: "56.21Z",
        activite_principale_registre_metier: null,
        annee_tranche_effectif_salarie: null,
        adresse: "17 RUE JACQUES KABLE 75018 PARIS",
        caractere_employeur: "N",
        cedex: null,
        code_pays_etranger: null,
        code_postal: "75018",
        commune: "75118",
        complement_adresse: null,
        coordonnees: "48.88604899999999,2.3614610000000003",
        date_creation: "2021-02-01",
        date_debut_activite: "2021-02-01",
        date_fermeture: null,
        date_mise_a_jour: null,
        date_mise_a_jour_insee: "2024-03-30T05:13:23",
        departement: "75",
        distribution_speciale: null,
        epci: "200054781",
        est_siege: true,
        etat_administratif: "A",
        geo_adresse: null,
        geo_id: null,
        indice_repetition: null,
        latitude: "48.88604899999999",
        libelle_cedex: null,
        libelle_commune: "PARIS",
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: "JACQUES KABLE",
        liste_enseignes: null,
        liste_finess: null,
        liste_id_bio: null,
        liste_idcc: null,
        liste_id_organisme_formation: null,
        liste_rge: null,
        liste_uai: null,
        longitude: "2.3614610000000003",
        nom_commercial: "ANTOINE ET LEO",
        numero_voie: "17",
        region: "11",
        siret: "89320859500015",
        statut_diffusion_etablissement: "O",
        tranche_effectif_salarie: null,
        type_voie: "RUE",
      },
      activite_principale: "56.21Z",
      categorie_entreprise: "PME",
      caractere_employeur: null,
      annee_categorie_entreprise: "2021",
      date_creation: "2021-02-01",
      date_fermeture: null,
      date_mise_a_jour: "2024-06-27T11:04:46",
      date_mise_a_jour_insee: "2024-03-22T14:26:06",
      date_mise_a_jour_rne: "2024-01-14T03:49:13",
      dirigeants: [
        {
          nom: "BOUILLON",
          prenoms: "LEO",
          annee_de_naissance: null,
          date_de_naissance: null,
          qualite: null,
          nationalite: null,
          type_dirigeant: "personne physique",
        },
      ],
      etat_administratif: "A",
      nature_juridique: "1000",
      section_activite_principale: "I",
      tranche_effectif_salarie: null,
      annee_tranche_effectif_salarie: null,
      statut_diffusion: "O",
      matching_etablissements: [
        {
          activite_principale: "56.21Z",
          annee_tranche_effectif_salarie: null,
          adresse: "17 RUE JACQUES KABLE 75018 PARIS",
          caractere_employeur: "N",
          code_postal: "75018",
          commune: "75118",
          date_creation: "2021-02-01",
          date_debut_activite: "2021-02-01",
          date_fermeture: null,
          epci: "200054781",
          est_siege: true,
          etat_administratif: "A",
          geo_id: null,
          latitude: "48.88604899999999",
          libelle_commune: "PARIS",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "2.3614610000000003",
          nom_commercial: "ANTOINE ET LEO",
          region: "11",
          siret: "89320859500015",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: null,
        },
      ],
      finances: {},
      complements: {
        collectivite_territoriale: null,
        convention_collective_renseignee: false,
        liste_idcc: null,
        egapro_renseignee: false,
        est_association: false,
        est_bio: false,
        est_entrepreneur_individuel: true,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_organisme_formation: false,
        est_qualiopi: false,
        liste_id_organisme_formation: null,
        est_rge: false,
        est_service_public: false,
        est_siae: false,
        est_societe_mission: false,
        est_uai: false,
        identifiant_association: null,
        statut_entrepreneur_spectacle: null,
        type_siae: null,
      },
    },
  ],
  total_results: 2,
  page: 1,
  per_page: 25,
  total_pages: 1,
};

export const searchWithMultiplePostalCodeMockResponse = {
  results: [
    {
      siren: "711017137",
      nom_complet: "CHARLES BOUILLON",
      nom_raison_sociale: null,
      sigle: null,
      nombre_etablissements: 1,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: "47.89Z",
        activite_principale_registre_metier: null,
        annee_tranche_effectif_salarie: null,
        adresse: "47 RUE MESLAY 75003 PARIS",
        caractere_employeur: "N",
        cedex: null,
        code_pays_etranger: null,
        code_postal: "75003",
        commune: "75103",
        complement_adresse: null,
        coordonnees: "48.86809,2.3578890000000006",
        date_creation: "1971-02-20",
        date_debut_activite: "2008-01-01",
        date_fermeture: null,
        date_mise_a_jour: null,
        date_mise_a_jour_insee: "2024-03-30T13:18:19",
        departement: "75",
        distribution_speciale: null,
        epci: "200054781",
        est_siege: true,
        etat_administratif: "A",
        geo_adresse: null,
        geo_id: null,
        indice_repetition: null,
        latitude: "48.86809",
        libelle_cedex: null,
        libelle_commune: "PARIS",
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: "MESLAY",
        liste_enseignes: null,
        liste_finess: null,
        liste_id_bio: null,
        liste_idcc: null,
        liste_id_organisme_formation: null,
        liste_rge: null,
        liste_uai: null,
        longitude: "2.3578890000000006",
        nom_commercial: null,
        numero_voie: "47",
        region: "11",
        siret: "71101713700011",
        statut_diffusion_etablissement: "O",
        tranche_effectif_salarie: null,
        type_voie: "RUE",
      },
      activite_principale: "47.89Z",
      categorie_entreprise: "PME",
      caractere_employeur: null,
      annee_categorie_entreprise: "2021",
      date_creation: "1971-02-20",
      date_fermeture: null,
      date_mise_a_jour: "2024-06-27T09:58:34",
      date_mise_a_jour_insee: "2024-03-22T14:26:06",
      date_mise_a_jour_rne: "2024-01-13T13:39:31",
      dirigeants: [
        {
          nom: "BOUILLON",
          prenoms: "CHARLES",
          annee_de_naissance: null,
          date_de_naissance: null,
          qualite: null,
          nationalite: null,
          type_dirigeant: "personne physique",
        },
      ],
      etat_administratif: "A",
      nature_juridique: "1000",
      section_activite_principale: "G",
      tranche_effectif_salarie: null,
      annee_tranche_effectif_salarie: null,
      statut_diffusion: "O",
      matching_etablissements: [
        {
          activite_principale: "47.89Z",
          annee_tranche_effectif_salarie: null,
          adresse: "47 RUE MESLAY 75003 PARIS",
          caractere_employeur: "N",
          code_postal: "75003",
          commune: "75103",
          date_creation: "1971-02-20",
          date_debut_activite: "2008-01-01",
          date_fermeture: null,
          epci: "200054781",
          est_siege: true,
          etat_administratif: "A",
          geo_id: null,
          latitude: "48.86809",
          libelle_commune: "PARIS",
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "2.3578890000000006",
          nom_commercial: null,
          region: "11",
          siret: "71101713700011",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: null,
        },
      ],
      finances: {},
      complements: {
        collectivite_territoriale: null,
        convention_collective_renseignee: false,
        liste_idcc: null,
        egapro_renseignee: false,
        est_association: false,
        est_bio: false,
        est_entrepreneur_individuel: true,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_organisme_formation: false,
        est_qualiopi: false,
        liste_id_organisme_formation: null,
        est_rge: false,
        est_service_public: false,
        est_siae: false,
        est_societe_mission: false,
        est_uai: false,
        identifiant_association: null,
        statut_entrepreneur_spectacle: null,
        type_siae: null,
      },
    },
  ],
  total_results: 1,
  page: 1,
  per_page: 25,
  total_pages: 1,
};

export const searchWithSiretMockResponse = {
  results: [
    {
      siren: "227605409",
      nom_complet: "DEPARTEMENT DE LA SEINE MARITIME",
      nom_raison_sociale: "DEPARTEMENT DE LA SEINE MARITIME",
      sigle: null,
      nombre_etablissements: 212,
      nombre_etablissements_ouverts: 169,
      siege: {
        activite_principale: "84.11Z",
        activite_principale_registre_metier: null,
        annee_tranche_effectif_salarie: "2021",
        adresse: "HOTEL DU DEPARTEMENT QUAI JEAN MOULIN 76100 ROUEN",
        caractere_employeur: "O",
        cedex: null,
        code_pays_etranger: null,
        code_postal: "76100",
        commune: "76540",
        complement_adresse: "HOTEL DU DEPARTEMENT",
        coordonnees: "49.43515299999997,1.092435000000001",
        date_creation: "1983-03-01",
        date_debut_activite: "2008-01-01",
        date_fermeture: null,
        date_mise_a_jour: null,
        date_mise_a_jour_insee: "2024-03-30T07:38:58",
        departement: "76",
        distribution_speciale: null,
        epci: "200023414",
        est_siege: true,
        etat_administratif: "A",
        geo_adresse: null,
        geo_id: null,
        indice_repetition: null,
        latitude: "49.43515299999997",
        libelle_cedex: null,
        libelle_commune: "ROUEN",
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: "JEAN MOULIN",
        liste_enseignes: null,
        liste_finess: ["760031500", "760039735"],
        liste_id_bio: null,
        liste_idcc: ["5021", "9999"],
        liste_id_organisme_formation: null,
        liste_rge: null,
        liste_uai: null,
        longitude: "1.092435000000001",
        nom_commercial: null,
        numero_voie: null,
        region: "28",
        siret: "22760540900019",
        statut_diffusion_etablissement: "O",
        tranche_effectif_salarie: "51",
        type_voie: "QUAI",
      },
      activite_principale: "84.11Z",
      categorie_entreprise: "ETI",
      caractere_employeur: null,
      annee_categorie_entreprise: "2021",
      date_creation: "1961-01-01",
      date_fermeture: null,
      date_mise_a_jour: "2024-06-27T07:53:43",
      date_mise_a_jour_insee: "2024-03-22T14:26:06",
      date_mise_a_jour_rne: null,
      dirigeants: [],
      etat_administratif: "A",
      nature_juridique: "7220",
      section_activite_principale: "O",
      tranche_effectif_salarie: "52",
      annee_tranche_effectif_salarie: "2021",
      statut_diffusion: "O",
      matching_etablissements: [
        {
          activite_principale: "84.11Z",
          annee_tranche_effectif_salarie: "2021",
          adresse: "HOTEL DU DEPARTEMENT QUAI JEAN MOULIN 76100 ROUEN",
          caractere_employeur: "O",
          code_postal: "76100",
          commune: "76540",
          date_creation: "1983-03-01",
          date_debut_activite: "2008-01-01",
          date_fermeture: null,
          epci: "200023414",
          est_siege: true,
          etat_administratif: "A",
          geo_id: null,
          latitude: "49.43515299999997",
          libelle_commune: "ROUEN",
          liste_enseignes: null,
          liste_finess: ["760031500", "760039735"],
          liste_id_bio: null,
          liste_idcc: ["5021", "9999"],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: "1.092435000000001",
          nom_commercial: null,
          region: "28",
          siret: "22760540900019",
          statut_diffusion_etablissement: "O",
          tranche_effectif_salarie: "51",
        },
      ],
      finances: {},
      complements: {
        collectivite_territoriale: {
          code: "76D",
          code_insee: "76",
          elus: [
            {
              nom: "BOUILLON",
              prenoms: "Christophe",
              annee_de_naissance: "1969-03",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "CANU",
              prenoms: "Pierrette",
              annee_de_naissance: "1948-12",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "LECORDIER",
              prenoms: "Nathalie",
              annee_de_naissance: "1963-11",
              fonction: "3ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "MARTIN",
              prenoms: "Pascal",
              annee_de_naissance: "1960-03",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "METOT",
              prenoms: "Dominique",
              annee_de_naissance: "1957-04",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "MOUTIER LECERF",
              prenoms: "Murielle",
              annee_de_naissance: "1958-07",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "LAMIRAY",
              prenoms: "David",
              annee_de_naissance: "1972-12",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "MANZANARES",
              prenoms: "Brigitte",
              annee_de_naissance: "1950-01",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "MARCHE",
              prenoms: "Frédéric",
              annee_de_naissance: "1964-02",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "MEZRAR",
              prenoms: "Nadia",
              annee_de_naissance: "1969-02",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "GRELAUD",
              prenoms: "Laurent",
              annee_de_naissance: "1963-06",
              fonction: "8ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "GROULT",
              prenoms: "Séverine",
              annee_de_naissance: "1976-05",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "GAUTIER",
              prenoms: "André",
              annee_de_naissance: "1965-06",
              fonction: "2ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "VANDECANDELAERE",
              prenoms: "Imelda",
              annee_de_naissance: "1963-11",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "FOURNIER",
              prenoms: "Maryline",
              annee_de_naissance: "1966-01",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "LANGLOIS",
              prenoms: "Nicolas",
              annee_de_naissance: "1983-09",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "LESAGE",
              prenoms: "Julie",
              annee_de_naissance: "1978-04",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "MARIE",
              prenoms: "Didier",
              annee_de_naissance: "1960-05",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "GARRAUD",
              prenoms: "Valérie",
              annee_de_naissance: "1961-06",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "JACQUES",
              prenoms: "Laurent",
              annee_de_naissance: "1968-08",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "BAZILLE",
              prenoms: "Alain",
              annee_de_naissance: "1951-08",
              fonction: "4ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "TESSIER",
              prenoms: "Dominique",
              annee_de_naissance: "1955-03",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "DECOUDRE",
              prenoms: "Joël",
              annee_de_naissance: "1956-03",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "LUCOT AVRIL",
              prenoms: "Virginie",
              annee_de_naissance: "1974-06",
              fonction: "5ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "DIALLO",
              prenoms: "Tacko",
              annee_de_naissance: "1983-07",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "ROULY",
              prenoms: "Nicolas",
              annee_de_naissance: "1976-08",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "DUVAL",
              prenoms: "Christian",
              annee_de_naissance: "1958-07",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "THIBAUDEAU-RAINOT",
              prenoms: "Florence",
              annee_de_naissance: "1970-10",
              fonction: "1er Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "DUBOST",
              prenoms: "Jérôme",
              annee_de_naissance: "1975-07",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "MOREL",
              prenoms: "Christine",
              annee_de_naissance: "1962-02",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "BRUNEAU",
              prenoms: "Alban",
              annee_de_naissance: "1976-01",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "HERVÉ",
              prenoms: "Sophie",
              annee_de_naissance: "1976-07",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "COUPPEY",
              prenoms: "Louisa",
              annee_de_naissance: "1969-06",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "CRAMOISAN",
              prenoms: "Pascal",
              annee_de_naissance: "1963-10",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "FIRMIN LE BODO",
              prenoms: "Agnès",
              annee_de_naissance: "1968-11",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "TEISSERE",
              prenoms: "Patrick",
              annee_de_naissance: "1957-07",
              fonction: "12ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "MSICA GUEROUT",
              prenoms: "Christelle",
              annee_de_naissance: "1968-07",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "SAINT MARTIN",
              prenoms: "Florent",
              annee_de_naissance: "1977-11",
              fonction: "14ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "COTTEREAU",
              prenoms: "Chantal",
              annee_de_naissance: "1961-10",
              fonction: "9ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "RENOUX",
              prenoms: "Vincent",
              annee_de_naissance: "1978-04",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "DEMAZURE",
              prenoms: "Julien",
              annee_de_naissance: "1987-06",
              fonction: "10ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "DURAMÉ",
              prenoms: "Delphine",
              annee_de_naissance: "1975-04",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "BELLANGER",
              prenoms: "Bertrand",
              annee_de_naissance: "1959-12",
              fonction: "Président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "FLAVIGNY",
              prenoms: "Catherine",
              annee_de_naissance: "1950-05",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "BERTRAND",
              prenoms: "Nicolas",
              annee_de_naissance: "1982-09",
              fonction: "6ème Vice-président du conseil départemental",
              sexe: "M",
            },
            {
              nom: "BILOQUET",
              prenoms: "Armelle",
              annee_de_naissance: "1970-01",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "COUTEY",
              prenoms: "Guillaume",
              annee_de_naissance: "1977-10",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "LARGILLET",
              prenoms: "Agnès",
              annee_de_naissance: "1977-12",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "CORITON",
              prenoms: "Bastien",
              annee_de_naissance: "1981-09",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "RENOU",
              prenoms: "Patricia",
              annee_de_naissance: "1967-02",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "DURANDE",
              prenoms: "Florence",
              annee_de_naissance: "1959-02",
              fonction: "13ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "ROCHE",
              prenoms: "Olivier",
              annee_de_naissance: "1969-04",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "CAREL",
              prenoms: "Pierre",
              annee_de_naissance: "1960-11",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "GOUJON",
              prenoms: "Charlotte",
              annee_de_naissance: "1983-01",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "FOUQUET",
              prenoms: "Marie",
              annee_de_naissance: "1973-10",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "RASSE LAMBRECQ",
              prenoms: "Valentin",
              annee_de_naissance: "1995-09",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "BEREGOVOY",
              prenoms: "Jean-Michel",
              annee_de_naissance: "1966-05",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "HEROUIN-LEAUTEY",
              prenoms: "Florence",
              annee_de_naissance: "1972-12",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "DUTARTE",
              prenoms: "Caroline",
              annee_de_naissance: "1964-02",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "MARTOT",
              prenoms: "Stéphane",
              annee_de_naissance: "1972-11",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "BOTTE",
              prenoms: "Séverine",
              annee_de_naissance: "1982-01",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "MOYSE",
              prenoms: "Joachim",
              annee_de_naissance: "1969-07",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "GUERIN",
              prenoms: "David",
              annee_de_naissance: "1966-01",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "GUEROULT",
              prenoms: "Claire",
              annee_de_naissance: "1970-03",
              fonction: "11ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "LHEUREUX",
              prenoms: "Jérôme",
              annee_de_naissance: "1960-03",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "SINEAU-PATRY",
              prenoms: "Cécile",
              annee_de_naissance: "1968-02",
              fonction: "7ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "PAWELSKI",
              prenoms: "Léa",
              annee_de_naissance: "1990-11",
              fonction: null,
              sexe: "F",
            },
            {
              nom: "RAGACHE",
              prenoms: "Alexis",
              annee_de_naissance: "1971-02",
              fonction: null,
              sexe: "M",
            },
            {
              nom: "GEST",
              prenoms: "Severine",
              annee_de_naissance: "1971-06",
              fonction: "15ème Vice-président du conseil départemental",
              sexe: "F",
            },
            {
              nom: "TERRIER",
              prenoms: "Didier",
              annee_de_naissance: "1954-04",
              fonction: null,
              sexe: "M",
            },
          ],
          niveau: "departement",
        },
        convention_collective_renseignee: true,
        liste_idcc: ["5021", "3228", "9999"],
        egapro_renseignee: false,
        est_association: false,
        est_bio: false,
        est_entrepreneur_individuel: false,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: true,
        est_organisme_formation: false,
        est_qualiopi: false,
        liste_id_organisme_formation: null,
        est_rge: false,
        est_service_public: true,
        est_siae: false,
        est_societe_mission: false,
        est_uai: false,
        identifiant_association: null,
        statut_entrepreneur_spectacle: null,
        type_siae: null,
      },
    },
  ],
  total_results: 1,
  page: 1,
  per_page: 25,
  total_pages: 1,
};
