jobs:
  runs:
    build-app:
      use: build
      env:
        - name: NEXT_PUBLIC_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: SENTRY_DSN
      with:
        buildArgs:
          NEXT_PUBLIC_CDTN_ENV: development
          NEXT_PUBLIC_BUCKET_FOLDER: "preview"
          NEXT_PUBLIC_BUCKET_SITEMAP_FOLDER: "sitemap"
          NEXT_PUBLIC_BUCKET_URL: https://cdtn-dev-public.s3.gra.io.cloud.ovh.net
          NEXT_PUBLIC_PIWIK_SITE_ID: "3"
          NEXT_PUBLIC_PIWIK_URL: https://matomo.fabrique.social.gouv.fr
          NEXT_PUBLIC_COMMIT: "{{.Values.global.sha}}"
          NEXT_PUBLIC_SITE_URL: "https://{{.Values.global.host}}"
          NEXT_PUBLIC_SENTRY_DSN: "$NEXT_PUBLIC_SENTRY_DSN"
          SENTRY_RELEASE: "{{.Values.global.branchSlug32}}"
          SENTRY_ORG: incubateur
          SENTRY_PROJECT: fabnum-code-du-travail-numerique
          SENTRY_URL: https://sentry2.fabrique.social.gouv.fr
          NEXT_PUBLIC_ES_INDEX_PREFIX: "cdtn-preprod"
          NEXT_PUBLIC_BRANCH_NAME_SLUG: "{{.Values.global.branchSlug32}}"
        secrets:
          sentry_auth_token:
            secretName: sentry
            secretKey: SENTRY_AUTH_TOKEN
          elasticsearch_token_api:
            secretName: www-secret
            secretKey: ELASTICSEARCH_TOKEN_API
          elasticsearch_url:
            secretName: www-secret
            secretKey: ELASTICSEARCH_URL

app:
  env:
    - name: "NEXT_PUBLIC_BRANCH_NAME_SLUG"
      value: "{{.Values.global.branchSlug32}}"
