jobs:
  runs:
    build-app:
      use: build
      with:
        buildArgs:
          NEXT_PUBLIC_SENTRY_DSN: https://81b6e3d265cf736588f894040d265705@sentry.fabrique.social.gouv.fr/107
          NEXT_PUBLIC_SENTRY_ENV: dev
          NEXT_PUBLIC_SENTRY_RELEASE: "{{.Values.global.sha}}"
          NEXT_PUBLIC_BUCKET_DEFAULT_FOLDER: "default"
          NEXT_PUBLIC_BUCKET_SITEMAP_FOLDER: "sitemap"
          NEXT_PUBLIC_BUCKET_URL: https://cdtn-prod-public.s3.gra.io.cloud.ovh.net/preview
          NEXT_PUBLIC_PIWIK_SITE_ID: "3"
          NEXT_PUBLIC_PIWIK_URL: https://matomo.fabrique.social.gouv.fr
          NEXT_PUBLIC_COMMIT: "{{.Values.global.sha}}"
          NEXT_PUBLIC_SITE_URL: "https://{{.Values.global.host}}"
          NEXT_PUBLIC_SENTRY_ORG: "incubateur"
          NEXT_PUBLIC_SENTRY_PROJECT: "code-du-travail-numerique-v2"
          NEXT_PUBLIC_SENTRY_URL: "https://sentry.fabrique.social.gouv.fr"
          NEXT_PUBLIC_ES_INDEX_PREFIX: "cdtn-preprod"
          NEXT_PUBLIC_BRANCH_NAME_SLUG: "{{.Values.global.branchSlug32}}"
        secrets:
          sentry_auth_token:
            secretName: www-secret
            secretKey: SENTRY_AUTH_TOKEN
          elasticsearch_token_api:
            secretName: www-secret
            secretKey: ELASTICSEARCH_TOKEN_API
          elasticsearch_url:
            secretName: www-secret
            secretKey: ELASTICSEARCH_URL

app:
  env:
    - name: "NEXT_PUBLIC_BRANCH_NAME_SLUG"
      value: "{{.Values.global.branchSlug32}}"
