jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_SENTRY_DSN: https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
          NEXT_PUBLIC_SENTRY_ENV: production
          NEXT_PUBLIC_SENTRY_RELEASE: "{{.Values.global.imageTag}}"
          NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT: "true"
          NEXT_PUBLIC_AZURE_BASE_URL: https://cdtnadminprod.blob.core.windows.net
          NEXT_PUBLIC_AZURE_CONTAINER: cdtn
          NEXT_PUBLIC_PIWIK_SITE_ID: "4"
          NEXT_PUBLIC_PIWIK_URL: https://matomo.fabrique.social.gouv.fr
          NEXT_PUBLIC_COMMIT: "{{.Values.global.sha}}"
          NEXT_PUBLIC_SITE_URL: https://code.travail.gouv.fr
          NEXT_PUBLIC_SENTRY_ORG: "incubateur"
          NEXT_PUBLIC_SENTRY_PROJECT: "code-du-travail-numerique"
          NEXT_PUBLIC_SENTRY_URL: "https://sentry.fabrique.social.gouv.fr/"
          NEXT_PUBLIC_ES_INDEX_PREFIX: "cdtn-prod"
        secrets:
          sentry_auth_token:
            secretName: www-secret
            secretKey: SENTRY_AUTH_TOKEN
          elasticsearch_token_api:
            secretName: www-secret
            secretKey: ELASTICSEARCH_TOKEN_API
          elasticsearch_url:
            secretName: www-secret
            secretKey: ELASTICSEARCH_URL

app:
  host: code.travail.gouv.fr
  redirectFrom:
    - www.code.travail.gouv.fr
    - code.travail.fabrique.social.gouv.fr
  autoscale:
    minReplicas: 2
    maxReplicas: 10
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 300m
      memory: 1536Mi
