app:
  host: code.travail.gouv.fr
  redirectFrom:
    - www.code.travail.gouv.fr
    - code.travail.fabrique.social.gouv.fr
  resources:
    limits:
      cpu: 900m
      memory: 1536Mi
    requests:
      cpu: 800m
      memory: 1280Mi
    annotations:
      oblik.socialgouv.io/min-request-cpu: 800m
      oblik.socialgouv.io/min-request-memory: 1280Mi
      oblik.socialgouv.io/min-limit-cpu: 900m
      oblik.socialgouv.io/min-limit-memory: 1536Mi
