jobs:
  runs:
    build-app:
      use: build
      env:
        - name: NEXT_PUBLIC_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: SENTRY_DSN
      with:
        buildArgs:
          NEXT_PUBLIC_CDTN_ENV: production
          NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT: "true"
          NEXT_PUBLIC_BUCKET_FOLDER: "published"
          NEXT_PUBLIC_BUCKET_SITEMAP_FOLDER: "sitemap"
          NEXT_PUBLIC_BUCKET_URL: https://cdtn-prod-public.s3.gra.io.cloud.ovh.net
          NEXT_PUBLIC_PIWIK_SITE_ID: "4"
          NEXT_PUBLIC_PIWIK_URL: https://matomo.fabrique.social.gouv.fr
          NEXT_PUBLIC_COMMIT: "{{.Values.global.sha}}"
          NEXT_PUBLIC_SITE_URL: https://code.travail.gouv.fr
          NEXT_PUBLIC_SENTRY_DSN: "$NEXT_PUBLIC_SENTRY_DSN"
          NEXT_PUBLIC_SENTRY_ENV: production
          SENTRY_RELEASE: "{{.Values.global.imageTag}}"
          SENTRY_ORG: incubateur
          SENTRY_PROJECT: fabnum-code-du-travail-numerique
          SENTRY_URL: https://sentry2.fabrique.social.gouv.fr
          NEXT_PUBLIC_ES_INDEX_PREFIX: "cdtn-prod"
        secrets:
          sentry_auth_token:
            secretName: sentry
            secretKey: SENTRY_AUTH_TOKEN
          elasticsearch_token_api:
            secretName: www-secret
            secretKey: ELASTICSEARCH_TOKEN_API
          elasticsearch_url:
            secretName: www-secret
            secretKey: ELASTICSEARCH_URL

app:
  host: code.travail.gouv.fr
  redirectFrom:
    - www.code.travail.gouv.fr
    - code.travail.fabrique.social.gouv.fr
  resources:
    limits:
      cpu: 900m
      memory: 1536Mi
    requests:
      cpu: 800m
      memory: 1280Mi
    annotations:
      oblik.socialgouv.io/min-request-cpu: 800m
      oblik.socialgouv.io/min-request-memory: 1280Mi
      oblik.socialgouv.io/min-limit-cpu: 900m
      oblik.socialgouv.io/min-limit-memory: 1536Mi
