app-frontend:
  host: code.travail.gouv.fr
  redirectFrom:
    - www.code.travail.gouv.fr
    - code.travail.fabrique.social.gouv.fr
  autoscale:
    minReplicas: 2
    maxReplicas: 10
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 768Mi
