import {
  FormuleFactory,
  SupportedCcIndemniteLicenciement,
} from "../../../plugins";
import { CatPro2216 } from "../../../plugins/formule/2216_commerces_detail_alimentation";

describe("Indemnité légale de licenciement avec une formule personnalisée et expliquée pour la CC 2216", () => {
  test.each`
    category               | isEconomicFiring | age   | seniority | expectedFormula                                                                                                                                                                                                                               | expectedExplanations
    ${CatPro2216.employes} | ${false}         | ${50} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.employes} | ${true}          | ${50} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.employes} | ${true}          | ${51} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.employes} | ${false}         | ${50} | ${8 / 12} | ${"1 / 4 * Sref * A"}                                                                                                                                                                                                                         | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.employes} | ${true}          | ${50} | ${8 / 12} | ${"1 / 4 * Sref * A"}                                                                                                                                                                                                                         | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.employes} | ${true}          | ${51} | ${8 / 12} | ${"1 / 4 * Sref * A + ( 20% * (1 / 4 * Sref * A) )"}                                                                                                                                                                                          | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)", "20% : majoration pour motif économique"]}
    ${CatPro2216.employes} | ${false}         | ${50} | ${11}     | ${"(1 / 4 * Sref * A1 + 1 / 3 * Sref * A2)"}                                                                                                                                                                                                  | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au delà de 10 ans (1 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.employes} | ${true}          | ${50} | ${11}     | ${"(1 / 4 * Sref * A1 + 1 / 3 * Sref * A2)"}                                                                                                                                                                                                  | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au delà de 10 ans (1 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.employes} | ${true}          | ${51} | ${11}     | ${"(1 / 4 * Sref * A1 + 1 / 3 * Sref * A2) + ( 20% * (1 / 4 * Sref * A) + 20% * (1 / 3 * Sref * A) )"}                                                                                                                                        | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au delà de 10 ans (1 an)", "Sref : Salaire de référence (1000 €)", "20% : majoration pour motif économique"]}
    ${CatPro2216.agents}   | ${false}         | ${50} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.agents}   | ${true}          | ${50} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.agents}   | ${true}          | ${51} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.agents}   | ${false}         | ${50} | ${8 / 12} | ${"1 / 4 * Sref * A"}                                                                                                                                                                                                                         | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.agents}   | ${true}          | ${50} | ${8 / 12} | ${"1 / 4 * Sref * A"}                                                                                                                                                                                                                         | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.agents}   | ${true}          | ${51} | ${8 / 12} | ${"1 / 4 * Sref * A + ( 20% * (1 / 4 * Sref * A) )"}                                                                                                                                                                                          | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)", "20% : majoration pour motif économique"]}
    ${CatPro2216.agents}   | ${false}         | ${50} | ${11}     | ${"(1 / 4 * Sref * A1 + 1 / 3 * Sref * A2)"}                                                                                                                                                                                                  | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au delà de 10 ans (1 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.agents}   | ${true}          | ${50} | ${11}     | ${"(1 / 4 * Sref * A1 + 1 / 3 * Sref * A2)"}                                                                                                                                                                                                  | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au delà de 10 ans (1 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.agents}   | ${true}          | ${51} | ${11}     | ${"(1 / 4 * Sref * A1 + 1 / 3 * Sref * A2) + ( 20% * (1 / 4 * Sref * A) + 20% * (1 / 3 * Sref * A) )"}                                                                                                                                        | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au delà de 10 ans (1 an)", "Sref : Salaire de référence (1000 €)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${false}         | ${50} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.cadres}   | ${true}          | ${50} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.cadres}   | ${true}          | ${51} | ${0}      | ${""}                                                                                                                                                                                                                                         | ${[]}
    ${CatPro2216.cadres}   | ${false}         | ${50} | ${8 / 12} | ${"1 / 4 * Sref * A"}                                                                                                                                                                                                                         | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)"]}
    ${CatPro2216.cadres}   | ${true}          | ${50} | ${8 / 12} | ${"1 / 4 * Sref * A + ( 20% * (1 / 4 * Sref * A) )"}                                                                                                                                                                                          | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${true}          | ${51} | ${8 / 12} | ${"1 / 4 * Sref * A + ( 20% * (1 / 4 * Sref * A) )"}                                                                                                                                                                                          | ${["A : Ancienneté totale (0.67 an)", "Sref : Salaire de référence (1000 €)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${false}         | ${50} | ${8}      | ${"( 3 / 10 * Sref * A1 )"}                                                                                                                                                                                                                   | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (8 ans)"]}
    ${CatPro2216.cadres}   | ${true}          | ${50} | ${8}      | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) )"}                                                                                                                                                                                | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (8 ans)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${true}          | ${51} | ${8}      | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) )"}                                                                                                                                                                                | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (8 ans)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${false}         | ${50} | ${11}     | ${"( 3 / 10 * Sref * A1 ) + ( 4 / 10 * Sref * A2 )"}                                                                                                                                                                                          | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (1 an)"]}
    ${CatPro2216.cadres}   | ${true}          | ${50} | ${11}     | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) ) + ( 4 / 10 * Sref * A2 ) + ( 20% * ( 4 / 10 * Sref * A2 ))"}                                                                                                                     | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (1 an)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${true}          | ${51} | ${11}     | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) ) + ( 4 / 10 * Sref * A2 ) + ( 20% * ( 4 / 10 * Sref * A2 ))"}                                                                                                                     | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (1 an)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${false}         | ${50} | ${22}     | ${"( 3 / 10 * Sref * A1 ) + ( 4 / 10 * Sref * A2 ) + ( 5 / 10 * Sref * A3 )"}                                                                                                                                                                 | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (10 ans)", "A3 : Années de présence pour la tranche de 20 ans à 40 ans (2 ans)"]}
    ${CatPro2216.cadres}   | ${true}          | ${50} | ${22}     | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) ) + ( 4 / 10 * Sref * A2 ) + ( 20% * ( 4 / 10 * Sref * A2 )) + ( 5 / 10 * Sref * A3 ) + ( 20% * ( 5 / 10 * Sref * A3 ))"}                                                          | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (10 ans)", "A3 : Années de présence pour la tranche de 20 ans à 40 ans (2 ans)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${true}          | ${51} | ${22}     | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) ) + ( 4 / 10 * Sref * A2 ) + ( 20% * ( 4 / 10 * Sref * A2 )) + ( 5 / 10 * Sref * A3 ) + ( 20% * ( 5 / 10 * Sref * A3 ))"}                                                          | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (10 ans)", "A3 : Années de présence pour la tranche de 20 ans à 40 ans (2 ans)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${false}         | ${50} | ${44}     | ${"( 3 / 10 * Sref * A1 ) + ( 4 / 10 * Sref * A2 ) + ( 5 / 10 * Sref * A3 ) + ( 1 / 3 * Sref * A4 )"}                                                                                                                                         | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (10 ans)", "A3 : Années de présence pour la tranche de 20 ans à 40 ans (20 ans)", "A4: Années de présence pour la tranche au-delà de 40 ans (4 ans)"]}
    ${CatPro2216.cadres}   | ${true}          | ${50} | ${44}     | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) ) + ( 4 / 10 * Sref * A2 ) + ( 20% * ( 4 / 10 * Sref * A2 )) + ( 5 / 10 * Sref * A3 ) + ( 20% * ( 5 / 10 * Sref * A3 )) + ( 1 / 3 * Sref * A4 ) + ( 20% * ( 1 / 3 * Sref * A4 ))"} | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (10 ans)", "A3 : Années de présence pour la tranche de 20 ans à 40 ans (20 ans)", "A4: Années de présence pour la tranche au-delà de 40 ans (4 ans)", "20% : majoration pour motif économique"]}
    ${CatPro2216.cadres}   | ${true}          | ${51} | ${44}     | ${"( 3 / 10 * Sref * A1 ) + ( 20% * ( 3 / 10 * Sref * A1 ) ) + ( 4 / 10 * Sref * A2 ) + ( 20% * ( 4 / 10 * Sref * A2 )) + ( 5 / 10 * Sref * A3 ) + ( 20% * ( 5 / 10 * Sref * A3 )) + ( 1 / 3 * Sref * A4 ) + ( 20% * ( 1 / 3 * Sref * A4 ))"} | ${["A1 : Années de présence pour la tranche jusqu'à 10 ans (10 ans)", "A2 : Années de présence pour la tranche de 10 à 20 ans (10 ans)", "A3 : Années de présence pour la tranche de 20 ans à 40 ans (20 ans)", "A4: Années de présence pour la tranche au-delà de 40 ans (4 ans)", "20% : majoration pour motif économique"]}
  `(
    "Formule $expectedFormula avec $seniority ans, catégorie $category, type de licenciement $typeLicenciement => explications $expectedExplanations",
    ({
      category,
      seniority,
      expectedFormula,
      expectedExplanations,
      age,
      isEconomicFiring,
    }) => {
      const formula = new FormuleFactory().create(
        SupportedCcIndemniteLicenciement.IDCC2216
      );

      const result = formula.computeFormula({
        age,
        category,
        isEconomicFiring,
        refSalary: 1000,
        seniority,
      });

      expect(result.formula).toEqual(expectedFormula);
      expect(result.explanations).toEqual(expectedExplanations);
    }
  );
});
