import {
  BreakIcon,
  ConditionsIcon,
  ConflictsIcon,
  ContractIcon,
  DepartIcon,
  DifficultiesIcon,
  EmploymentIcon,
  FormationIcon,
  HealthIcon,
  HiringIcon,
  HolidaysIcon,
  NegoIcon,
  ResignationIcon,
  RetirementIcon,
  RisksIcon,
  SalaryIcon,
  SpecificIcon,
  TimeIcon,
} from "./themes";

export const ThemeIcons = {
  Break: BreakIcon,
  Conditions: ConditionsIcon,
  Conflicts: ConflictsIcon,
  Contract: ContractIcon,
  Depart: DepartIcon,
  Difficulties: DifficultiesIcon,
  Employment: EmploymentIcon,
  Formation: FormationIcon,
  Health: HealthIcon,
  Hiring: HiringIcon,
  Holidays: HolidaysIcon,
  Nego: NegoIcon,
  Resignation: ResignationIcon,
  Retirement: RetirementIcon,
  Risks: RisksIcon,
  Salary: SalaryIcon,
  Specific: SpecificIcon,
  Time: TimeIcon,
} as const;
