Test on deployed branch:
  stage: .post
  image: ghcr.io/socialgouv/docker/code-du-travail-frontend-e2e:6.18.0
  except:
    refs:
      # Don't run on release
      - tags
    variables:
      # Don't run when deploying in production
      - $PRODUCTION
  environment:
    name: ${CI_COMMIT_REF_SLUG}${AUTO_DEVOPS_DEV_ENVIRONMENT_NAME}
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - packages/code-du-travail-frontend-e2e/node_modules
      - $CI_PROJECT_DIR/.yarn
  retry: 2

  before_script:
    - echo $CI_ENVIRONMENT_NAME
    - echo $CI_ENVIRONMENT_URL
    - echo $CI_ENVIRONMENT_SLUG
    #- source ./.gitlab-ci/env.sh
    - CODECEPT_BASEURL=${CI_ENVIRONMENT_URL}
    - cd ./packages/code-du-travail-frontend-e2e
    - |-
      retry=60;
      while
        ! wget -q -O - "$@" "${CI_ENVIRONMENT_URL}/api/version"  | grep "${CI_COMMIT_REF_NAME}" &&
        [[ $(( retry-- )) -gt 0 ]];
      do echo "Waiting for frontend to be ready" ; sleep 3 ; done ;
      [ "$retry" -eq "-1" ] && exit 1

  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile
    #
    - echo "${CODECEPT_BASEURL}"
    #
    - CODECEPT_BASEURL=${CODECEPT_BASEURL} yarn test

  artifacts:
    when: always
    paths:
      - ./packages/code-du-travail-frontend-e2e/output
    expire_in: 1 week
