export const blocs = {
  1: { label: "Salaires minima hiérarchiques" },
  10: { label: "Période d'essai : conditions et renouvellement" },
  11: { label: "Contrats de travail : poursuite" },
  12: { label: "Salarié temporaire : poursuite" },
  13: { label: "Salarié porté : rémunération" },
  14: { important: true, label: "Risques professionnels : prévention" },
  15: { important: true, label: "Emploi des travailleurs handicapés" },
  16: { important: true, label: "Délégués syndicaux" },
  17: { important: true, label: "Primes travaux dangereux et insalubres" },
  2: { label: "Classifications" },
  3: { label: "Fonds financement paritarisme : mutualisation" },
  4: { label: "Fonds formation professionnelle : mutualisation" },
  5: { label: "Prévoyance" },
  6: { label: "Durée du travail, répartition et aménagement des horaires" },
  7: { label: "Contrats à durée déterminée et contrats de travail temporaire" },
  8: { label: "Contrat à durée indéterminée de chantier ou d'opération" },
  9: { label: "Egalité professionnelle femme-homme" },
};
