export const blocs = {
  1: { label: "Salaires minima hiérarchiques" },
  2: { label: "Classifications" },
  3: { label: "Fond financement paritarisme : mutualisation" },
  4: { label: "Fond formation professionnelle : mutualisation" },
  5: { label: "Prévoyance" },
  6: { label: "Durée du travail, répartition et aménagement des horaires" },
  7: { label: "Contrats à durée déterminée et contrats de travail temporaire" },
  8: { label: "Contrat à durée indéterminée de chantier ou d'opération" },
  9: { label: "Egalité professionnelle femme-homme" },
  10: { label: "Période d'essai : conditions et renouvellement" },
  11: { label: "Contrats de travail : poursuite" },
  12: { label: "Salarié temporaire : poursuite" },
  13: { label: "Salarié porté : rémunération" },
  14: { label: "Risques professionnels : prévention", important: true },
  15: { label: "Emploi des travailleurs handicapés", important: true },
  16: { label: "Délégués syndicaux", important: true },
  17: { label: "Primes travaux dangereux et insalubres", important: true },
};
