export enum ListSimulator {
  PREAVIS_DEMISSION,
  PREAVIS_LICENCIEMENT,
  PREAVIS_DEPART_RETRAITE,
  PREAVIS_MISE_RETRAITE,
  PREAVIS_RETRAITE_BOTH,
  INDEMNITE_LICENCIEMENT,
  HEURES_RECHERCHE_EMPLOI,
  INDEMNITE_PRECARITE,
}
