export type Tool = {
  date: string;
  icon: string;
  order: number;
  action: string;
  metaTitle: string;
  questions?: string[];
  description: string;
  displayTitle: string;
  breadcrumbs: Record<string, string | number>[];
  cdtnId: string;
  excludeFromSearch: boolean;
  id: string;
  isPublished: boolean;
  metaDescription: string;
  slug: string;
  source: string;
  text: string;
  title: string;
  title_vector: number[];
  _id: string;
  displayTool?: boolean;
};
