export const removeCCNumberFromSlug = (slug: string): string =>
  slug.split("-").slice(1).join("-");

export const ultraShortNameCc: {
  [idcc: number]: string;
} = {
  16: "Transports routiers",
  29: "Hospitalisation à but non lucratif FEHAP",
  44: "Chimie industrie",
  86: "Publicité",
  176: "Pharmaceutique industrie",
  275: "Transport aérien personnel au sol",
  292: "Plasturgie",
  413: "Personnes inadaptées et handicapées établissements",
  573: "Commerces de gros",
  675: "Habillement commerce succursales",
  787: "Experts-comptables et commissaires aux comptes",
  843: "Boulangerie pâtisserie entreprises artisanales",
  1043: "Gardiens concierges et employés d'immeubles",
  1090: "Automobile services",
  1147: "Cabinets médicaux",
  1266: "Restauration de collectivités",
  1351: "Prévention sécurité entreprises",
  1404: "Tracteurs matériels agricoles commerce réparation",
  1483: "Habillement articles textiles commerce de détail",
  1486: "Bureaux d'études techniques",
  1501: "Restauration rapide",
  1505: "Commerce de détail alimentaire non spécialisé",
  1516: "Formation organismes",
  1517: "Commerce détail non alimentaire",
  1518: "Animation",
  1527: "Immobilier",
  1596: "Bâtiment ouvriers (jusqu'à 10 salariés)",
  1597: "Bâtiment ouvriers (plus de 10 salariés)",
  1606: "Bricolage vente au détail en libre-service",
  1672: "Assurances sociétés",
  1702: "Travaux publics ouvriers",
  1979: "Hôtels cafés restaurants",
  1996: "Pharmacie d'officine",
  2098: "Prestataires de services secteur tertiaire",
  2120: "Banque",
  2148: "Télécommunications",
  2216: "Commerce détail et gros à prédominance alimentaire",
  2264: "Hospitalisation privée",
  2420: "Bâtiment cadres",
  2511: "Sport",
  2596: "Coiffure",
  2609: "Bâtiment ETAM",
  2614: "Travaux publics ETAM",
  2941: "Aide soins services à domicile (BAD)",
  3043: "Propreté entreprises et services associés",
  3127: "Services à la personne entreprises",
  3239: "Particuliers employeurs et emploi à domicile",
  3248: "CC nationale de la métallurgie",
  1480: "Journalistes",
};
