export const fulltextPayload = {
  total_results: 2,
  total_pages: 1,
  per_page: 10,
  page: 1,
  etablissement: [
    {
      id: 112277319,
      siren: "802585703",
      siret: "80258570300035",
      nic: "00035",
      l1_normalisee: "CORSO BALARD",
      l2_normalisee: null,
      l3_normalisee: null,
      l4_normalisee: "28 RUE DE VENISE",
      l5_normalisee: null,
      l6_normalisee: "75004 PARIS 4",
      l7_normalisee: null,
      l1_declaree: null,
      l2_declaree: null,
      l3_declaree: null,
      l4_declaree: "28 RUE DE VENISE",
      l5_declaree: null,
      l6_declaree: "75004 PARIS 4",
      l7_declaree: null,
      numero_voie: "28",
      indice_repetition: null,
      type_voie: "RUE",
      libelle_voie: "DE VENISE",
      code_postal: "75004",
      cedex: null,
      region: "11",
      libelle_region: null,
      departement: "75",
      arrondissement: "1",
      canton: null,
      commune: "104",
      libelle_commune: "PARIS 4E ARRONDISSEMENT",
      departement_unite_urbaine: null,
      taille_unite_urbaine: null,
      numero_unite_urbaine: null,
      etablissement_public_cooperation_intercommunale: null,
      tranche_commune_detaillee: "80",
      zone_emploi: null,
      is_siege: "1",
      enseigne: null,
      indicateur_champ_publipostage: "A",
      statut_prospection: null,
      date_introduction_base_diffusion: "201901",
      nature_entrepreneur_individuel: null,
      libelle_nature_entrepreneur_individuel: null,
      activite_principale: "6420Z",
      libelle_activite_principale: "Activités des sociétés holding",
      date_validite_activite_principale: null,
      tranche_effectif_salarie: null,
      libelle_tranche_effectif_salarie: null,
      tranche_effectif_salarie_centaine_pret: null,
      date_validite_effectif_salarie: null,
      origine_creation: null,
      date_creation: "20190102",
      date_debut_activite: "20190102",
      nature_activite: null,
      lieu_activite: null,
      type_magasin: null,
      is_saisonnier: null,
      modalite_activite_principale: null,
      caractere_productif: null,
      participation_particuliere_production: null,
      caractere_auxiliaire: null,
      nom_raison_sociale: "CORSO BALARD",
      sigle: null,
      nom: null,
      prenom: null,
      civilite: null,
      numero_rna: null,
      nic_siege: "00035",
      region_siege: "11",
      departement_commune_siege: "75104",
      email: null,
      nature_juridique_entreprise: "5720",
      libelle_nature_juridique_entreprise:
        "Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle",
      activite_principale_entreprise: "6420Z",
      libelle_activite_principale_entreprise: "Activités des sociétés holding",
      date_validite_activite_principale_entreprise: null,
      activite_principale_registre_metier: null,
      is_ess: null,
      date_ess: null,
      tranche_effectif_salarie_entreprise: "12",
      libelle_tranche_effectif_salarie_entreprise: null,
      tranche_effectif_salarie_entreprise_centaine_pret: null,
      date_validite_effectif_salarie_entreprise: "2017",
      categorie_entreprise: "PME",
      date_creation_entreprise: "201405",
      date_introduction_base_diffusion_entreprise: "201901",
      indice_monoactivite_entreprise: null,
      modalite_activite_principale_entreprise: null,
      caractere_productif_entreprise: null,
      date_validite_rubrique_niveau_entreprise_esa: null,
      tranche_chiffre_affaire_entreprise_esa: null,
      activite_principale_entreprise_esa: null,
      premiere_activite_secondaire_entreprise_esa: null,
      deuxieme_activite_secondaire_entreprise_esa: null,
      troisieme_activite_secondaire_entreprise_esa: null,
      quatrieme_activite_secondaire_entreprise_esa: null,
      nature_mise_a_jour: null,
      indicateur_mise_a_jour_1: null,
      indicateur_mise_a_jour_2: null,
      indicateur_mise_a_jour_3: null,
      date_mise_a_jour: "2019-03-07T16:40:35",
      created_at: "2019-09-01T04:00:35.000Z",
      updated_at: "2019-09-01T04:00:35.000Z",
      longitude: "2.350955",
      latitude: "48.861184",
      geo_score: "0.58",
      geo_type: "housenumber",
      geo_adresse: "28 Rue de Venise 75004 Paris",
      geo_id: "ADRNIVX_0000000270765963",
      geo_ligne: "G",
      geo_l4: "28 RUE DE VENISE",
      geo_l5: null
    },
    {
      id: 108527673,
      siren: "802585703",
      siret: "80258570300027",
      nic: "00027",
      l1_normalisee: "CORSO BALARD",
      l2_normalisee: "52 56",
      l3_normalisee: null,
      l4_normalisee: "52 RUE BALARD",
      l5_normalisee: null,
      l6_normalisee: "75015 PARIS 15",
      l7_normalisee: null,
      l1_declaree: null,
      l2_declaree: null,
      l3_declaree: null,
      l4_declaree: "52 RUE BALARD",
      l5_declaree: null,
      l6_declaree: "75015 PARIS 15",
      l7_declaree: null,
      numero_voie: "52",
      indice_repetition: null,
      type_voie: "RUE",
      libelle_voie: "BALARD",
      code_postal: "75015",
      cedex: null,
      region: "11",
      libelle_region: null,
      departement: "75",
      arrondissement: "1",
      canton: null,
      commune: "115",
      libelle_commune: "PARIS 15E ARRONDISSEMENT",
      departement_unite_urbaine: null,
      taille_unite_urbaine: null,
      numero_unite_urbaine: null,
      etablissement_public_cooperation_intercommunale: null,
      tranche_commune_detaillee: "80",
      zone_emploi: null,
      is_siege: "0",
      enseigne: null,
      indicateur_champ_publipostage: "A",
      statut_prospection: null,
      date_introduction_base_diffusion: "201609",
      nature_entrepreneur_individuel: null,
      libelle_nature_entrepreneur_individuel: null,
      activite_principale: "5610A",
      libelle_activite_principale: "Restauration traditionnelle",
      date_validite_activite_principale: null,
      tranche_effectif_salarie: "00",
      libelle_tranche_effectif_salarie: null,
      tranche_effectif_salarie_centaine_pret: null,
      date_validite_effectif_salarie: "2016",
      origine_creation: null,
      date_creation: "20160801",
      date_debut_activite: "20160901",
      nature_activite: null,
      lieu_activite: null,
      type_magasin: null,
      is_saisonnier: null,
      modalite_activite_principale: null,
      caractere_productif: null,
      participation_particuliere_production: null,
      caractere_auxiliaire: null,
      nom_raison_sociale: "CORSO BALARD",
      sigle: null,
      nom: null,
      prenom: null,
      civilite: null,
      numero_rna: null,
      nic_siege: "00035",
      region_siege: "11",
      departement_commune_siege: "75104",
      email: null,
      nature_juridique_entreprise: "5720",
      libelle_nature_juridique_entreprise:
        "Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle",
      activite_principale_entreprise: "6420Z",
      libelle_activite_principale_entreprise: "Activités des sociétés holding",
      date_validite_activite_principale_entreprise: null,
      activite_principale_registre_metier: null,
      is_ess: null,
      date_ess: null,
      tranche_effectif_salarie_entreprise: "12",
      libelle_tranche_effectif_salarie_entreprise: null,
      tranche_effectif_salarie_entreprise_centaine_pret: null,
      date_validite_effectif_salarie_entreprise: "2017",
      categorie_entreprise: "PME",
      date_creation_entreprise: "201405",
      date_introduction_base_diffusion_entreprise: "201901",
      indice_monoactivite_entreprise: null,
      modalite_activite_principale_entreprise: null,
      caractere_productif_entreprise: null,
      date_validite_rubrique_niveau_entreprise_esa: null,
      tranche_chiffre_affaire_entreprise_esa: null,
      activite_principale_entreprise_esa: null,
      premiere_activite_secondaire_entreprise_esa: null,
      deuxieme_activite_secondaire_entreprise_esa: null,
      troisieme_activite_secondaire_entreprise_esa: null,
      quatrieme_activite_secondaire_entreprise_esa: null,
      nature_mise_a_jour: null,
      indicateur_mise_a_jour_1: null,
      indicateur_mise_a_jour_2: null,
      indicateur_mise_a_jour_3: null,
      date_mise_a_jour: "2018-09-29T13:41:41",
      created_at: "2019-09-01T03:27:10.000Z",
      updated_at: "2019-09-01T03:27:10.000Z",
      longitude: "2.27767",
      latitude: "48.84137",
      geo_score: "0.56",
      geo_type: "housenumber",
      geo_adresse: "52 Rue Balard 75015 Paris",
      geo_id: "ADRNIVX_0000000270801227",
      geo_ligne: "G",
      geo_l4: "52 RUE BALARD",
      geo_l5: null
    }
  ],
  spellcheck: null,
  suggestions: ["corso balard"]
};

export const siretPayload = {
  etablissement: {
    id: 108527673,
    siren: "802585703",
    siret: "80258570300027",
    nic: "00027",
    l1_normalisee: "CORSO BALARD",
    l2_normalisee: "52 56",
    l3_normalisee: null,
    l4_normalisee: "52 RUE BALARD",
    l5_normalisee: null,
    l6_normalisee: "75015 PARIS 15",
    l7_normalisee: null,
    l1_declaree: null,
    l2_declaree: null,
    l3_declaree: null,
    l4_declaree: "52 RUE BALARD",
    l5_declaree: null,
    l6_declaree: "75015 PARIS 15",
    l7_declaree: null,
    numero_voie: "52",
    indice_repetition: null,
    type_voie: "RUE",
    libelle_voie: "BALARD",
    code_postal: "75015",
    cedex: null,
    region: "11",
    libelle_region: null,
    departement: "75",
    arrondissement: "1",
    canton: null,
    commune: "115",
    libelle_commune: "PARIS 15E ARRONDISSEMENT",
    departement_unite_urbaine: null,
    taille_unite_urbaine: null,
    numero_unite_urbaine: null,
    etablissement_public_cooperation_intercommunale: null,
    tranche_commune_detaillee: "80",
    zone_emploi: null,
    is_siege: "0",
    enseigne: null,
    indicateur_champ_publipostage: "A",
    statut_prospection: null,
    date_introduction_base_diffusion: "201609",
    nature_entrepreneur_individuel: null,
    libelle_nature_entrepreneur_individuel: null,
    activite_principale: "5610A",
    libelle_activite_principale: "Restauration traditionnelle",
    date_validite_activite_principale: null,
    tranche_effectif_salarie: "00",
    libelle_tranche_effectif_salarie: null,
    tranche_effectif_salarie_centaine_pret: null,
    date_validite_effectif_salarie: "2016",
    origine_creation: null,
    date_creation: "20160801",
    date_debut_activite: "20160901",
    nature_activite: null,
    lieu_activite: null,
    type_magasin: null,
    is_saisonnier: null,
    modalite_activite_principale: null,
    caractere_productif: null,
    participation_particuliere_production: null,
    caractere_auxiliaire: null,
    nom_raison_sociale: "CORSO BALARD",
    sigle: null,
    nom: null,
    prenom: null,
    civilite: null,
    numero_rna: null,
    nic_siege: "00035",
    region_siege: "11",
    departement_commune_siege: "75104",
    email: null,
    nature_juridique_entreprise: "5720",
    libelle_nature_juridique_entreprise:
      "Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle",
    activite_principale_entreprise: "6420Z",
    libelle_activite_principale_entreprise: "Activités des sociétés holding",
    date_validite_activite_principale_entreprise: null,
    activite_principale_registre_metier: null,
    is_ess: null,
    date_ess: null,
    tranche_effectif_salarie_entreprise: "12",
    libelle_tranche_effectif_salarie_entreprise: null,
    tranche_effectif_salarie_entreprise_centaine_pret: null,
    date_validite_effectif_salarie_entreprise: "2017",
    categorie_entreprise: "PME",
    date_creation_entreprise: "201405",
    date_introduction_base_diffusion_entreprise: "201901",
    indice_monoactivite_entreprise: null,
    modalite_activite_principale_entreprise: null,
    caractere_productif_entreprise: null,
    date_validite_rubrique_niveau_entreprise_esa: null,
    tranche_chiffre_affaire_entreprise_esa: null,
    activite_principale_entreprise_esa: null,
    premiere_activite_secondaire_entreprise_esa: null,
    deuxieme_activite_secondaire_entreprise_esa: null,
    troisieme_activite_secondaire_entreprise_esa: null,
    quatrieme_activite_secondaire_entreprise_esa: null,
    nature_mise_a_jour: null,
    indicateur_mise_a_jour_1: null,
    indicateur_mise_a_jour_2: null,
    indicateur_mise_a_jour_3: null,
    date_mise_a_jour: "2018-09-29T13:41:41",
    created_at: "2019-09-01T03:27:10.000Z",
    updated_at: "2019-09-01T03:27:10.000Z",
    longitude: "2.27767",
    latitude: "48.84137",
    geo_score: "0.56",
    geo_type: "housenumber",
    geo_adresse: "52 Rue Balard 75015 Paris",
    geo_id: "ADRNIVX_0000000270801227",
    geo_ligne: "G",
    geo_l4: "52 RUE BALARD",
    geo_l5: null
  }
};

export const siretIdccPayload = [
  {
    siret: "80258570300027",
    conventions: [
      {
        active: true,
        date_publi: "1997-12-07T00:00:00.000Z",
        etat: "VIGUEUR_ETEN",
        id: "KALICONT000005635534",
        mtime: 1562700340,
        nature: "IDCC",
        num: "1979",
        texte_de_base: "KALITEXT000005670044",
        title:
          "Convention collective nationale des hôtels, cafés restaurants (HCR) du 30 avril 1997",
        effectif: 580085,
        shortTitle: "Hôtels Cafés Restaurants (Hcr)",
        url:
          "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635534"
      }
    ]
  }
];
