extends:
  - "@socialgouv/eslint-config-recommended"

overrides:
  - files: ["step_definitions/**/*.js"]
    globals:
      Given: readonly
      When: readonly
      Then: readonly
      actor: readonly
      by: readonly
      inject: readonly
      locate: readonly
      pause: readonly
      secret: readonly
      session: readonly
      Feature: readonly
      Scenario: readonly
      xScenario: readonly
      Before: readonly
      After: readonly
      BeforeSuite: readonly
      AfterSuite: readonly
      within: readonly
      Data: readonly
      DataTable: readonly
      Helper: readonly
