global:
  registry: harbor.fabrique.social.gouv.fr

app-frontend:
  ~chart: app
  ~needs: [build-frontend]
  imagePackage: frontend
  imageProject: cdtn
  probesPath: /api/health
  autoscale:
    minReplicas: 2
    maxReplicas: 10
  envFrom:
    - secretRef:
        name: www-configmap
    - secretRef:
        name: www-secret

jobs:
  runs:
    build-frontend:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build@v1
      with:
        registrySecretRefName: harbor
        imagePackage: frontend
        imageProject: cdtn
        buildArgs:
          VERSION: "{{ $.Values.global.sha }}"
