jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      with:
        imagePackage: app

app:
  ~chart: app
  ~needs: [build-app]
  imagePackage: app
  imageProject: cdtn
  probesPath: /api/health
  containerSecurityContext:
    readOnlyRootFilesystem: true
  envFrom:
    - configMapRef:
        name: www-configmap
    - secretRef:
        name: www-secret
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  annotations:
    oblik.socialgouv.io/min-request-cpu: 400m
    oblik.socialgouv.io/min-request-memory: 512Mi
    oblik.socialgouv.io/min-limit-cpu: 400m
    oblik.socialgouv.io/min-limit-memory: 1024Mi
  volumes:
    - name: tmp
      emptyDir: {}
    - name: next
      emptyDir: {}
  volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /app/packages/code-du-travail-frontend/.next
      name: next
  initContainers:
    - name: copy-next
      image: "{{ .Values.global.registry }}/{{ .Values.global.projectName }}/{{
        .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
      command: ["/bin/sh", "-c"]
      args:
        - cp -r /app/packages/code-du-travail-frontend/.next/* /mnt/next;
      volumeMounts:
        - name: next
          mountPath: /mnt/next
