jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      with:
        imagePackage: app

app:
  ~chart: app
  ~needs: [build-app]
  imagePackage: app
  imageProject: cdtn
  probesPath: /api/health
  envFrom:
    - configMapRef:
        name: www-configmap
    - secretRef:
        name: www-secret
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
