app:
  ~chart: app
  imagePackage: app
  imageProject: cdtn
  probesPath: /api/health
  livenessProbe:
    failureThreshold: 15
    httpGet:
      path: /api/health/
      port: http
      scheme: HTTP
    initialDelaySeconds: 30  # Délai avant la première vérification après le démarrage du pod
    periodSeconds: 10         # Fréquence des vérifications
    successThreshold: 1
    timeoutSeconds: 10         # Temps maximum pour que l'endpoint réponde
  containerSecurityContext:
    readOnlyRootFilesystem: true
  envFrom:
    - configMapRef:
        name: www-configmap
    - secretRef:
        name: www-secret
  env:
    - name: SENTRY_AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          name: sentry
          key: SENTRY_AUTH_TOKEN
    - name: NEXT_PUBLIC_SENTRY_DSN
      valueFrom:
        secretKeyRef:
          name: sentry
          key: SENTRY_DSN
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  annotations:
    oblik.socialgouv.io/min-request-cpu: 400m
    oblik.socialgouv.io/min-request-memory: 512Mi
    oblik.socialgouv.io/min-limit-cpu: 400m
    oblik.socialgouv.io/min-limit-memory: 1024Mi
  volumes:
    - name: tmp
      emptyDir: {}
    - name: next
      emptyDir: {}
  volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /app/packages/code-du-travail-frontend/.next
      name: next
  initContainers:
    - name: copy-next
      image:
        "{{ .Values.global.registry }}/{{ .Values.global.projectName }}/{{
        .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
      command: ["/bin/sh", "-c"]
      args:
        - cp -r /app/packages/code-du-travail-frontend/.next/* /mnt/next;
      volumeMounts:
        - name: next
          mountPath: /mnt/next
