jobs:
  ~chart: jobs
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
    build-nginx:
      use: build
      with:
        imagePackage: nginx
        context: packages/nginx

app:
  ~chart: app
  ~needs: [build-app]
  imagePackage: app
  imageProject: cdtn
  probesPath: /api/health
  envFrom:
    - configMapRef:
        name: www-configmap
    - secretRef:
        name: www-secret
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  ingress:
    enabled: false

nginx:
  ~chart: app
  ~needs: [build-nginx]
  imagePackage: nginx
  host: "{{ .Values.global.host }}"
  containerPort: 8080
  probesPath: /live
  livenessProbe:
    httpGet:
      path: /live
      port: 8080
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
  lifecycle:
    preStop:
      exec:
        command: ["/pre-stop.sh"]
  resources:
    requests:
      cpu: 30m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 1G
