app:
  imagePackage: frontend
  imageProject: cdtn
  probesPath: /api/health
  envFrom:
    - secretRef:
        name: www-configmap
    - secretRef:
        name: www-secret
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
