#!/bin/sh
. "$(dirname $0)/_/husky.sh"

yarn lerna run \
  --exclude-dependents \
  --parallel prepush \
  --since origin/HEAD \
  --stream \
  ;

if git diff dev --name-only | grep --quiet ".k8s"
then
  yarn k8s
  yarn k8s prepush
fi
