#!/bin/sh
. "$(dirname $0)/_/husky.sh"

yarn lerna run \
  --exclude-dependents \
  --parallel prepush\
  --since master \
  --stream \
  ;

if git diff master --name-only | grep --quiet ".k8s"
then
  yarn k8s
  yarn k8s prepush
fi
