export const mockCarrefour = {
  entreprises: [
    {
      activitePrincipale:
        "Commerce de détail en magasin non spécialisé à prédominance alimentaire",
      activitePrincipaleUniteLegale: "47.11F",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2006-01-10",
      dateDebut: "2022-04-01",
      etablissements: 229,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "47.11F",
        address: "CENTRE COMMERCIAL VALENTIN AUX TETES 25480 ECOLE-VALENTIN",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "25212",
        codePostalEtablissement: "25480",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "ECOLE-VALENTIN",
        siret: "45132133501187",
      },
      highlightLabel:
        "<b><u>CARREFOUR</u></b> HYPERMARCHES <b><u>CARREOUR</u></b>",
      label: "CARREFOUR HYPERMARCHES CARREOUR",
      matching: 141,
      simpleLabel: "CARREFOUR HYPERMARCHES",
      siren: "451321335",
    },
    {
      activitePrincipale:
        "Commerce de gros non spécialisé de denrées, boissons et tabac",
      activitePrincipaleUniteLegale: "77.40Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1988-06-02",
      dateDebut: "2022-12-31",
      etablissements: 2646,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "46.39B",
        address: "ZI DE LA CRAU AV GABRIEL VOISIN 13300 SALON-DE-PROVENCE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "13103",
        codePostalEtablissement: "13300",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "SALON-DE-PROVENCE",
        siret: "34513048805172",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> PROXIMITE FRANCE",
      label: "CARREFOUR PROXIMITE FRANCE",
      matching: 18,
      simpleLabel: "CARREFOUR PROXIMITE FRANCE",
      siren: "345130488",
    },
    {
      activitePrincipale: "Activités des sièges sociaux",
      activitePrincipaleUniteLegale: "68.20B",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1975-01-01",
      dateDebut: "2023-09-04",
      etablissements: 204,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.10Z",
        address: "ZI RTE DE PARIS 14120 MONDEVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14437",
        codePostalEtablissement: "14120",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MONDEVILLE",
        siret: "67205008502051",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> FRANCE",
      label: "CARREFOUR FRANCE",
      matching: 1,
      simpleLabel: "CARREFOUR FRANCE",
      siren: "672050085",
    },
    {
      activitePrincipale: "Autre distribution de crédit",
      activitePrincipaleUniteLegale: "64.92Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5599",
      conventions: [
        {
          num: 478,
          shortTitle: "Sociétés financières",
          id: "KALICONT000005635810",
          title:
            "Convention collective nationale des sociétés financières du 22 novembre 1968",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635810",
          slug: "478-societes-financieres",
          contributions: false,
        },
        {
          num: 2120,
          shortTitle: "Banque",
          id: "KALICONT000005635780",
          title:
            "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
          slug: "2120-banque",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1978-01-01",
      dateDebut: "2022-09-22",
      etablissements: 210,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.92Z",
        address: "CENTRE COMMERCIAL CHE DE SAINT CLAUDE 06600 ANTIBES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "06004",
        codePostalEtablissement: "06600",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["0478"],
        libelleCommuneEtablissement: "ANTIBES",
        siret: "31381151500136",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> BANQUE",
      label: "CARREFOUR BANQUE",
      matching: 41,
      simpleLabel: "CARREFOUR BANQUE",
      siren: "313811515",
    },
    {
      activitePrincipale: "Activités des agences de voyage",
      activitePrincipaleUniteLegale: "79.11Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 3245,
          shortTitle: "Opérateurs de voyages et guides",
          id: "KALICONT000046139444",
          title:
            "Convention collective nationale des opérateurs de voyages et des guides du 19 avril 2022",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000046139444",
          slug: "3245-operateurs-de-voyages-et-guides",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1990-11-05",
      dateDebut: "2022-03-31",
      etablissements: 165,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "79.11Z",
        address: "CTRE COM CARREFOUR CHE DE SAINT CLAUDE 06600 ANTIBES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "06004",
        codePostalEtablissement: "06600",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["3245"],
        libelleCommuneEtablissement: "ANTIBES",
        siret: "37960197400239",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> VOYAGES",
      label: "CARREFOUR VOYAGES",
      matching: 101,
      simpleLabel: "CARREFOUR VOYAGES",
      siren: "379601974",
    },
    {
      activitePrincipale:
        "Commerce de gros non spécialisé de denrées, boissons et tabac",
      activitePrincipaleUniteLegale: "52.10B",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1999-12-07",
      dateDebut: "2022-08-01",
      etablissements: 73,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "46.39B",
        address:
          "PARC INDUSTRIEL DE LA PLAINE DE L'AIN ALL DES CEDRES 01150 SAINT-VULBAS",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "01390",
        codePostalEtablissement: "01150",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "SAINT-VULBAS",
        siret: "42824028700428",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> SUPPLY CHAIN",
      label: "CARREFOUR SUPPLY CHAIN",
      matching: 24,
      simpleLabel: "CARREFOUR SUPPLY CHAIN",
      siren: "428240287",
    },
    {
      activitePrincipale: "Vente à distance",
      activitePrincipaleUniteLegale: "47.91A",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5202",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2010-01-07",
      dateDebut: "2022-06-20",
      etablissements: 41,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "47.91A",
        address: "ZA DES 3 MOULINS 51 RUE HENRI LAUGIER 06600 ANTIBES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "06004",
        codePostalEtablissement: "06600",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "ANTIBES",
        siret: "51951457400275",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> DRIVE",
      label: "CARREFOUR DRIVE",
      matching: 4,
      simpleLabel: "CARREFOUR DRIVE",
      siren: "519514574",
    },
    {
      activitePrincipale:
        "Traitement de données, hébergement et activités connexes",
      activitePrincipaleUniteLegale: "62.01Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2000-12-19",
      dateDebut: "2022-10-19",
      etablissements: 21,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "63.11Z",
        address: "ZI RTE DE PARIS 14120 MONDEVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14437",
        codePostalEtablissement: "14120",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MONDEVILLE",
        siret: "43392911400018",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> SYSTEMES D'INFORMATION",
      label: "C.S.I. CARREFOUR SYSTEMES D'INFORMATION",
      matching: 3,
      simpleLabel: "CARREFOUR SYSTEMES D'INFORMATION",
      siren: "433929114",
    },
    {
      activitePrincipale: "Activités des sièges sociaux",
      activitePrincipaleUniteLegale: "70.10Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1999-12-07",
      dateDebut: "2022-10-25",
      etablissements: 19,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.10Z",
        address: "ZI RTE DE PARIS 14120 MONDEVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14437",
        codePostalEtablissement: "14120",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MONDEVILLE",
        siret: "42824035200016",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> ADMINISTRATIF FRANCE",
      label: "CARREFOUR ADMINISTRATIF FRANCE",
      matching: 3,
      simpleLabel: "CARREFOUR ADMINISTRATIF FRANCE",
      siren: "428240352",
    },
    {
      activitePrincipale:
        "Location et exploitation de biens immobiliers propres ou loués",
      activitePrincipaleUniteLegale: "68.20B",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 1527,
          shortTitle:
            "Immobilier : administrateurs de biens, sociétés immobilières, agents immobiliers",
          id: "KALICONT000005635413",
          title:
            "Convention collective nationale de l'immobilier, administrateurs de biens, sociétés immobilières, agents immobiliers, etc. (anciennement cabinets d'administrateurs de biens et des sociétés immobilières), du 9 septembre 1988. Etendue par arrêté du 24 février 1989 JORF 3 mars 1989. Mise à jour par avenant  n° 47 du 23 novembre 2010, JORF 18 juillet 2012 ",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635413",
          slug: "1527-immobilier-administrateurs-de-biens-societes-immobilieres-agents-immobi",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2006-12-04",
      dateDebut: "2023-01-09",
      etablissements: 10,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "68.20B",
        address:
          "C.C. CARREFOUR AIX LA PIOLINE 1175 RUE GUILLAUME DU VAIR 13290 AIX-EN-PROVENCE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "13001",
        codePostalEtablissement: "13290",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["1527"],
        libelleCommuneEtablissement: "AIX-EN-PROVENCE",
        siret: "49312339200109",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> PROPERTY GESTION",
      label: "CARREFOUR PROPERTY GESTION",
      matching: 6,
      simpleLabel: "CARREFOUR PROPERTY GESTION",
      siren: "493123392",
    },
    {
      activitePrincipale: "Agences immobilières",
      activitePrincipaleUniteLegale: "68.31Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5499",
      conventions: [
        {
          num: 1527,
          shortTitle:
            "Immobilier : administrateurs de biens, sociétés immobilières, agents immobiliers",
          id: "KALICONT000005635413",
          title:
            "Convention collective nationale de l'immobilier, administrateurs de biens, sociétés immobilières, agents immobiliers, etc. (anciennement cabinets d'administrateurs de biens et des sociétés immobilières), du 9 septembre 1988. Etendue par arrêté du 24 février 1989 JORF 3 mars 1989. Mise à jour par avenant  n° 47 du 23 novembre 2010, JORF 18 juillet 2012 ",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635413",
          slug: "1527-immobilier-administrateurs-de-biens-societes-immobilieres-agents-immobi",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1997-10-15",
      dateDebut: "2018-12-31",
      etablissements: 8,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "68.31Z",
        address: "1 BD DU SOUBEYRAN 48000 MENDE",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "48095",
        codePostalEtablissement: "48000",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["1527"],
        libelleCommuneEtablissement: "MENDE",
        siret: "41397622600089",
      },
      highlightLabel:
        "LE <b><u>CARREFOUR</u></b> DE L'IMMOBILIER ORPI LA LAUZE",
      label: "LE CARREFOUR DE L'IMMOBILIER ORPI LA LAUZE",
      matching: 3,
      simpleLabel: "LE CARREFOUR DE L'IMMOBILIER",
      siren: "413976226",
    },
    {
      activitePrincipale: "Autres activités de soutien aux entreprises n.c.a.",
      activitePrincipaleUniteLegale: "82.99Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1992-03-26",
      dateDebut: "2018-10-01",
      etablissements: 8,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "82.99Z",
        address: "93 AV DE PARIS 91300 MASSY",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "91377",
        codePostalEtablissement: "91300",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MASSY",
        siret: "38517158200088",
      },
      highlightLabel:
        "CMI <b><u>CARREFOUR</u></b> MARCHANDISES INTERNATIONALES",
      label: "CMI CARREFOUR MARCHANDISES INTERNATIONALES",
      matching: 1,
      simpleLabel: "CARREFOUR MARCHANDISES INTERNATIONALES",
      siren: "385171582",
    },
    {
      activitePrincipale:
        "Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé",
      activitePrincipaleUniteLegale: "47.76Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 1760,
          shortTitle: "Jardineries et graineteries",
          id: "KALICONT000005635938",
          title:
            "Convention collective nationale des jardineries et graineteries du 3 décembre 1993.  Etendue par arrêté du 6 juillet 1994 JORF 20 juillet 1994.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635938",
          slug: "1760-jardineries-et-graineteries",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1999-07-01",
      dateDebut: "2021-08-01",
      etablissements: 7,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "47.76Z",
        address: "57 RUE PIERRE SEMARD 62210 AVION",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "62065",
        codePostalEtablissement: "62210",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["1760"],
        libelleCommuneEtablissement: "AVION",
        siret: "42407112400020",
      },
      highlightLabel: "LE <b><u>CARREFOUR</u></b> DE LA FLEUR",
      label: "LE CARREFOUR DE LA FLEUR",
      matching: 4,
      simpleLabel: "LE CARREFOUR DE LA FLEUR",
      siren: "424071124",
    },
    {
      activitePrincipale:
        "Conseil pour les affaires et autres conseils de gestion",
      activitePrincipaleUniteLegale: "70.22Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5499",
      conventions: [
        {
          num: 1486,
          shortTitle:
            "Bureaux d'études techniques, cabinets d'ingénieurs-conseils et sociétés de conseils",
          id: "KALICONT000005635173",
          title:
            "Convention collective nationale des bureaux d'études techniques, des cabinets d'ingénieurs-conseils et des sociétés de conseils du 15 décembre 1987. ",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635173",
          slug: "1486-bureaux-detudes-techniques-cabinets-dingenieurs-conseils-et-societes-de",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2006-04-14",
      dateDebut: "2020-05-11",
      etablissements: 6,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.22Z",
        address: "13 CRS JEAN JAURES 38000 GRENOBLE",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "38185",
        codePostalEtablissement: "38000",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["1486"],
        libelleCommuneEtablissement: "GRENOBLE",
        siret: "49012454200062",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> DES COMPETENCES - C2",
      label: "CARREFOUR DES COMPETENCES - C2",
      matching: 1,
      simpleLabel: "CARREFOUR DES COMPETENCES - C2",
      siren: "490124542",
    },
    {
      activitePrincipale: "Activités des sièges sociaux",
      activitePrincipaleUniteLegale: "70.10Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1998-10-01",
      dateDebut: "2019-01-01",
      etablissements: 6,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.10Z",
        address: "93 AV DE PARIS 91300 MASSY",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "91377",
        codePostalEtablissement: "91300",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MASSY",
        siret: "42026584500065",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> PARTENARIAT INTERNATIONAL",
      label: "CARREFOUR PARTENARIAT INTERNATIONAL",
      matching: 1,
      simpleLabel: "CARREFOUR PARTENARIAT INTERNATIONAL",
      siren: "420265845",
    },
    {
      activitePrincipale: "Activités des organisations associatives n.c.a.",
      activitePrincipaleUniteLegale: "94.99Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "9220",
      conventions: [
        {
          num: 413,
          shortTitle:
            "Handicapés : établissements et services pour les personnes inadaptées et handicapées",
          id: "KALICONT000005635407",
          title:
            "Convention collective nationale de travail des etablissements et services pour personnes inadaptées et handicapées du 15 mars 1966. Mise à jour au 15 septembre 1976.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635407",
          slug: "413-handicapes-etablissements-et-services-pour-les-personnes-inadaptees-et-han",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1979-11-16",
      dateDebut: "2019-03-28",
      etablissements: 6,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "94.99Z",
        address: "10 RUE BAPTISTE MONNOYER 59800 LILLE",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "59350",
        codePostalEtablissement: "59800",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["0413"],
        libelleCommuneEtablissement: "LILLE",
        siret: "32230418900077",
      },
      highlightLabel:
        "CNAEMO <b><u>CARREFOUR</u></b> NATIONAL DE L'ACTION EDUCATIVE EN MILEU OUVERT",
      label: "CNAEMO CARREFOUR NATIONAL DE L'ACTION EDUCATIVE EN MILEU OUVERT",
      matching: 1,
      simpleLabel: "CARREFOUR NATIONAL DE L'ACTION EDUCATIVE EN MILEU OUVERT",
      siren: "322304189",
    },
    {
      activitePrincipale: "Commerce de gros de textiles",
      activitePrincipaleUniteLegale: "46.41Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2000-12-12",
      dateDebut: "2022-05-06",
      etablissements: 5,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "46.41Z",
        address: "93 AV DE PARIS 91300 MASSY",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "91377",
        codePostalEtablissement: "91300",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MASSY",
        siret: "43421213000059",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> IMPORT",
      label: "CARREFOUR IMPORT",
      matching: 1,
      simpleLabel: "CARREFOUR IMPORT",
      siren: "434212130",
    },
    {
      activitePrincipale:
        "Commerce de détail en magasin non spécialisé à prédominance alimentaire",
      activitePrincipaleUniteLegale: "47.11C",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5499",
      conventions: [
        {
          num: 1505,
          shortTitle: "Commerce de détail alimentaire non spécialisé",
          id: "KALICONT000005635421",
          title:
            "Convention collective nationale du commerce de détail alimentaire non spécialisé du 12 janvier 2021 (Avenant n° 138 du 12 janvier 2021) - Étendue par arrêté du 17 décembre 2021 JORF 23 décembre 2021",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635421",
          slug: "1505-commerce-de-detail-alimentaire-non-specialise",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2014-04-01",
      dateDebut: "2023-02-03",
      etablissements: 4,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "47.11C",
        address: "100 B AV DU 4 AOUT 1944 56000 VANNES",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "56260",
        codePostalEtablissement: "56000",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["1505"],
        libelleCommuneEtablissement: "VANNES",
        siret: "80120893500024",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> DES CONTINENTS",
      label: "CARREFOUR DES CONTINENTS",
      matching: 1,
      simpleLabel: "CARREFOUR DES CONTINENTS",
      siren: "801208935",
    },
    {
      activitePrincipale: "Activités des organisations associatives n.c.a.",
      activitePrincipaleUniteLegale: "94.99Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "9220",
      conventions: [
        {
          num: 1518,
          shortTitle:
            "Éducation, culture, loisirs et animation au service des territoires (ÉCLAT)",
          id: "KALICONT000005635177",
          title:
            "Convention collective nationale des métiers de l'éducation, de la culture, des loisirs et de l'animation agissant pour l'utilité sociale et environnementale, au service des territoires (ÉCLAT) du 28 juin 1988. Étendue par arrêté du 10 janvier 1989 JORF 13 janvier 1989",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635177",
          slug: "1518-education-culture-loisirs-et-animation-au-service-des-territoires-eclat",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1900-01-01",
      dateDebut: "2016-07-01",
      etablissements: 4,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "94.99Z",
        address: "MAISON DES ASSOCIATIONS G 29 RUE DRAYE DE MEYNE 26110 NYONS",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "26220",
        codePostalEtablissement: "26110",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["1518"],
        libelleCommuneEtablissement: "NYONS",
        siret: "77943252500045",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> DES HABITANTS DU NYONSAIS",
      label: "CARREFOUR DES HABITANTS DU NYONSAIS",
      matching: 1,
      simpleLabel: "CARREFOUR DES HABITANTS DU NYONSAIS",
      siren: "779432525",
    },
    {
      activitePrincipale: "Hébergement médicalisé",
      activitePrincipaleUniteLegale: "87.10A",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "9220",
      conventions: [
        {
          num: 29,
          shortTitle:
            "Hospitalisation privée : établissements privés d'hospitalisation, de soins, de cure et de garde à but non lucratif (FEHAP)",
          id: "KALICONT000005635234",
          title:
            "Convention collective nationale des etablissements privés d'hospitalisation, de soins, de cure et de garde à but non lucratif du 31 octobre 1951.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635234",
          slug: "29-hospitalisation-privee-etablissements-prives-dhospitalisation-de-soins-d",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1900-01-01",
      dateDebut: "2023-07-21",
      etablissements: 4,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "87.10A",
        address: "LE CHASSEUR 42530 SAINT-GENEST-LERPT",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "42223",
        codePostalEtablissement: "42530",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["0029"],
        libelleCommuneEtablissement: "SAINT-GENEST-LERPT",
        siret: "77640253900014",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> AMITIE ENTRAIDE PERSONNE AGEE",
      label: "CARREFOUR AMITIE ENTRAIDE PERSONNE AGEE",
      matching: 4,
      simpleLabel: "CARREFOUR AMITIE ENTRAIDE PERSONNE AGEE",
      siren: "776402539",
    },
  ],
};

export const mockOndo69007 = {
  entreprises: [
    {
      activitePrincipale:
        "Conseil pour les affaires et autres conseils de gestion",
      activitePrincipaleUniteLegale: "70.22Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5499",
      conventions: [
        {
          num: 1486,
          shortTitle:
            "Bureaux d'études techniques, cabinets d'ingénieurs-conseils et sociétés de conseils",
          id: "KALICONT000005635173",
          title:
            "Convention collective nationale des bureaux d'études techniques, des cabinets d'ingénieurs-conseils et des sociétés de conseils du 15 décembre 1987. ",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635173",
          slug: "1486-bureaux-detudes-techniques-cabinets-dingenieurs-conseils-et-societes-de",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2009-06-17",
      dateDebut: "2019-03-18",
      etablissements: 1,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.22Z",
        address: "3 RUE JANGOT 69007 LYON 7EME",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "69387",
        codePostalEtablissement: "69007",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["1486"],
        libelleCommuneEtablissement: "LYON 7EME",
        siret: "51347727300017",
      },
      highlightLabel: "BUENA <b><u>ONDA</u></b> WEB",
      label: "BUENA ONDA WEB",
      matching: 1,
      simpleLabel: "BUENA ONDA WEB",
      siren: "513477273",
    },
    {
      activitePrincipale: "Fabrication de pain et de pâtisserie fraîche",
      activitePrincipaleUniteLegale: "10.71C",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "1000",
      conventions: [
        {
          num: 843,
          shortTitle: "Boulangerie-pâtisserie (entreprises artisanales)",
          id: "KALICONT000005635886",
          title:
            "Convention collective nationale de la boulangerie-pâtisserie du 19 mars 1976.  Etendue par arrêté du 21 juin 1978 JONC 28 juillet 1978.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635886",
          slug: "843-boulangerie-patisserie-entreprises-artisanales",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2008-02-13",
      dateDebut: "2008-02-13",
      etablissements: 1,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "10.71C",
        address: "150 AV BERTHELOT 69007 LYON 7EME",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "69387",
        codePostalEtablissement: "69007",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["0843"],
        libelleCommuneEtablissement: "LYON 7EME",
        siret: "50280580700018",
      },
      highlightLabel: "MARC VERNIN <b><u>ONDO</u></b>",
      label: "MARC VERNIN ONDO",
      matching: 1,
      simpleLabel: "VERNIN",
      siren: "502805807",
    },
  ],
};

export const mock82129756100010 = {
  entreprises: [
    {
      activitePrincipale: "Restaurants et services de restauration mobile",
      activitePrincipaleUniteLegale: "56.10A",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 1979,
          shortTitle: "Hôtels, cafés, restaurants",
          id: "KALICONT000005635534",
          title:
            "Convention collective nationale des hôtels, cafés restaurants (HCR) du 30 avril 1997",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635534",
          slug: "1979-hotels-cafes-restaurants",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2016-06-30",
      dateDebut: "2023-01-11",
      etablissements: 1,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "56.10A",
        address: "22 BD DE CLICHY 75018 PARIS 18",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "75118",
        codePostalEtablissement: "75018",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["1979"],
        libelleCommuneEtablissement: "PARIS 18",
        siret: "82129756100010",
      },
      highlightLabel: "BOUILLON PIGALLE",
      label: "BOUILLON PIGALLE",
      matching: 1,
      simpleLabel: "BOUILLON PIGALLE",
      siren: "821297561",
    },
  ],
};

export const mockCarrefourBanque = {
  entreprises: [
    {
      activitePrincipale: "Autre distribution de crédit",
      activitePrincipaleUniteLegale: "64.92Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5599",
      conventions: [
        {
          num: 478,
          shortTitle: "Sociétés financières",
          id: "KALICONT000005635810",
          title:
            "Convention collective nationale des sociétés financières du 22 novembre 1968",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635810",
          slug: "478-societes-financieres",
          contributions: false,
        },
        {
          num: 2120,
          shortTitle: "Banque",
          id: "KALICONT000005635780",
          title:
            "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
          slug: "2120-banque",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1978-01-01",
      dateDebut: "2022-09-22",
      etablissements: 210,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.92Z",
        address: "CENTRE COMMERCIAL CHE DE SAINT CLAUDE 06600 ANTIBES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "06004",
        codePostalEtablissement: "06600",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["0478"],
        libelleCommuneEtablissement: "ANTIBES",
        siret: "31381151500136",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> <b><u>BANQUE</u></b>",
      label: "CARREFOUR BANQUE",
      matching: 41,
      simpleLabel: "CARREFOUR BANQUE",
      siren: "313811515",
    },
    {
      activitePrincipale:
        "Commerce de détail en magasin non spécialisé à prédominance alimentaire",
      activitePrincipaleUniteLegale: "47.11F",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2006-01-10",
      dateDebut: "2022-04-01",
      etablissements: 229,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "47.11F",
        address: "CENTRE COMMERCIAL VALENTIN AUX TETES 25480 ECOLE-VALENTIN",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "25212",
        codePostalEtablissement: "25480",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "ECOLE-VALENTIN",
        siret: "45132133501187",
      },
      highlightLabel:
        "<b><u>CARREFOUR</u></b> HYPERMARCHES <b><u>CARREOUR</u></b>",
      label: "CARREFOUR HYPERMARCHES CARREOUR",
      matching: 141,
      simpleLabel: "CARREFOUR HYPERMARCHES",
      siren: "451321335",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5599",
      conventions: [
        {
          num: 2120,
          shortTitle: "Banque",
          id: "KALICONT000005635780",
          title:
            "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
          slug: "2120-banque",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1955-01-01",
      dateDebut: "2022-09-06",
      etablissements: 41,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "12 PL SULLY 63400 CHAMALIERES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "63075",
        codePostalEtablissement: "63400",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2120"],
        libelleCommuneEtablissement: "CHAMALIERES",
        siret: "85520101800287",
      },
      highlightLabel: "<b><u>BANQUE</u></b> CHALUS <b><u>BAQUE</u></b>",
      label: "BANQUE CHALUS BAQUE",
      matching: 23,
      simpleLabel: "BANQUE CHALUS",
      siren: "855201018",
    },
    {
      activitePrincipale:
        "Commerce de gros non spécialisé de denrées, boissons et tabac",
      activitePrincipaleUniteLegale: "77.40Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1988-06-02",
      dateDebut: "2022-12-31",
      etablissements: 2646,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "46.39B",
        address: "ZI DE LA CRAU AV GABRIEL VOISIN 13300 SALON-DE-PROVENCE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "13103",
        codePostalEtablissement: "13300",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "SALON-DE-PROVENCE",
        siret: "34513048805172",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> PROXIMITE FRANCE",
      label: "CARREFOUR PROXIMITE FRANCE",
      matching: 18,
      simpleLabel: "CARREFOUR PROXIMITE FRANCE",
      siren: "345130488",
    },
    {
      activitePrincipale: "Activités des sièges sociaux",
      activitePrincipaleUniteLegale: "68.20B",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1975-01-01",
      dateDebut: "2023-09-04",
      etablissements: 204,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.10Z",
        address: "ZI RTE DE PARIS 14120 MONDEVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14437",
        codePostalEtablissement: "14120",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MONDEVILLE",
        siret: "67205008502051",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> FRANCE",
      label: "CARREFOUR FRANCE",
      matching: 1,
      simpleLabel: "CARREFOUR FRANCE",
      siren: "672050085",
    },
    {
      activitePrincipale: "Activités des agences de voyage",
      activitePrincipaleUniteLegale: "79.11Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 3245,
          shortTitle: "Opérateurs de voyages et guides",
          id: "KALICONT000046139444",
          title:
            "Convention collective nationale des opérateurs de voyages et des guides du 19 avril 2022",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000046139444",
          slug: "3245-operateurs-de-voyages-et-guides",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1990-11-05",
      dateDebut: "2022-03-31",
      etablissements: 165,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "79.11Z",
        address: "CTRE COM CARREFOUR CHE DE SAINT CLAUDE 06600 ANTIBES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "06004",
        codePostalEtablissement: "06600",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["3245"],
        libelleCommuneEtablissement: "ANTIBES",
        siret: "37960197400239",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> VOYAGES",
      label: "CARREFOUR VOYAGES",
      matching: 101,
      simpleLabel: "CARREFOUR VOYAGES",
      siren: "379601974",
    },
    {
      activitePrincipale:
        "Commerce de gros non spécialisé de denrées, boissons et tabac",
      activitePrincipaleUniteLegale: "52.10B",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1999-12-07",
      dateDebut: "2022-08-01",
      etablissements: 73,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "46.39B",
        address:
          "PARC INDUSTRIEL DE LA PLAINE DE L'AIN ALL DES CEDRES 01150 SAINT-VULBAS",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "01390",
        codePostalEtablissement: "01150",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "SAINT-VULBAS",
        siret: "42824028700428",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> SUPPLY CHAIN",
      label: "CARREFOUR SUPPLY CHAIN",
      matching: 24,
      simpleLabel: "CARREFOUR SUPPLY CHAIN",
      siren: "428240287",
    },
    {
      activitePrincipale: "Vente à distance",
      activitePrincipaleUniteLegale: "47.91A",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5202",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2010-01-07",
      dateDebut: "2022-06-20",
      etablissements: 41,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "47.91A",
        address: "ZA DES 3 MOULINS 51 RUE HENRI LAUGIER 06600 ANTIBES",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "06004",
        codePostalEtablissement: "06600",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "ANTIBES",
        siret: "51951457400275",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> DRIVE",
      label: "CARREFOUR DRIVE",
      matching: 4,
      simpleLabel: "CARREFOUR DRIVE",
      siren: "519514574",
    },
    {
      activitePrincipale:
        "Traitement de données, hébergement et activités connexes",
      activitePrincipaleUniteLegale: "62.01Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2000-12-19",
      dateDebut: "2022-10-19",
      etablissements: 21,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "63.11Z",
        address: "ZI RTE DE PARIS 14120 MONDEVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14437",
        codePostalEtablissement: "14120",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MONDEVILLE",
        siret: "43392911400018",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> SYSTEMES D'INFORMATION",
      label: "C.S.I. CARREFOUR SYSTEMES D'INFORMATION",
      matching: 3,
      simpleLabel: "CARREFOUR SYSTEMES D'INFORMATION",
      siren: "433929114",
    },
    {
      activitePrincipale: "Activités des sièges sociaux",
      activitePrincipaleUniteLegale: "70.10Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1999-12-07",
      dateDebut: "2022-10-25",
      etablissements: 19,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "70.10Z",
        address: "ZI RTE DE PARIS 14120 MONDEVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14437",
        codePostalEtablissement: "14120",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MONDEVILLE",
        siret: "42824035200016",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> ADMINISTRATIF FRANCE",
      label: "CARREFOUR ADMINISTRATIF FRANCE",
      matching: 3,
      simpleLabel: "CARREFOUR ADMINISTRATIF FRANCE",
      siren: "428240352",
    },
    {
      activitePrincipale:
        "Location et exploitation de biens immobiliers propres ou loués",
      activitePrincipaleUniteLegale: "68.20B",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 1527,
          shortTitle:
            "Immobilier : administrateurs de biens, sociétés immobilières, agents immobiliers",
          id: "KALICONT000005635413",
          title:
            "Convention collective nationale de l'immobilier, administrateurs de biens, sociétés immobilières, agents immobiliers, etc. (anciennement cabinets d'administrateurs de biens et des sociétés immobilières), du 9 septembre 1988. Etendue par arrêté du 24 février 1989 JORF 3 mars 1989. Mise à jour par avenant  n° 47 du 23 novembre 2010, JORF 18 juillet 2012 ",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635413",
          slug: "1527-immobilier-administrateurs-de-biens-societes-immobilieres-agents-immobi",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "2006-12-04",
      dateDebut: "2023-01-09",
      etablissements: 10,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "68.20B",
        address:
          "C.C. CARREFOUR AIX LA PIOLINE 1175 RUE GUILLAUME DU VAIR 13290 AIX-EN-PROVENCE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "13001",
        codePostalEtablissement: "13290",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["1527"],
        libelleCommuneEtablissement: "AIX-EN-PROVENCE",
        siret: "49312339200109",
      },
      highlightLabel: "<b><u>CARREFOUR</u></b> PROPERTY GESTION",
      label: "CARREFOUR PROPERTY GESTION",
      matching: 6,
      simpleLabel: "CARREFOUR PROPERTY GESTION",
      siren: "493123392",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5599",
      conventions: [
        {
          num: 2120,
          shortTitle: "Banque",
          id: "KALICONT000005635780",
          title:
            "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
          slug: "2120-banque",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1954-01-01",
      dateDebut: "2022-05-04",
      etablissements: 710,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "52 RUE JEAN MOULIN 69300 CALUIRE-ET-CUIRE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "69034",
        codePostalEtablissement: "69300",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2120"],
        libelleCommuneEtablissement: "CALUIRE-ET-CUIRE",
        siret: "95450797602532",
      },
      highlightLabel: "LYONNAISE DE <b><u>BANQUE</u></b>",
      label: "CIC LYONNAISE DE ... BANQUE",
      matching: 339,
      simpleLabel: "LYONNAISE DE BANQUE",
      siren: "954507976",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5599",
      conventions: [
        {
          num: 2120,
          shortTitle: "Banque",
          id: "KALICONT000005635780",
          title:
            "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
          slug: "2120-banque",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1955-01-01",
      dateDebut: "2022-04-26",
      etablissements: 464,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "8 RUE CONDE 16200 JARNAC",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "16167",
        codePostalEtablissement: "16200",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2120"],
        libelleCommuneEtablissement: "JARNAC",
        siret: "85580107201104",
      },
      highlightLabel: "CIC OUEST <b><u>BANQUE</u></b>",
      label: "CIC OUEST BANQUE",
      matching: 261,
      simpleLabel: "BANQUE CIC OUEST",
      siren: "855801072",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5560",
      conventions: [
        {
          num: 3210,
          shortTitle: "Banque populaire",
          id: "KALICONT000031197865",
          title: "Convention collective Banque populaire  du 15 juin 2015",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000031197865",
          slug: "3210-banque-populaire",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1957-01-01",
      dateDebut: "2023-06-01",
      etablissements: 458,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "10 AV DE LA REPUBLIQUE 14800 DEAUVILLE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "14220",
        codePostalEtablissement: "14800",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["3210"],
        libelleCommuneEtablissement: "DEAUVILLE",
        siret: "85750022702698",
      },
      highlightLabel: "<b><u>BANQUE</u></b> POPULAIRE GRAND OUEST",
      label: "BANQUE POPULAIRE GRAND OUEST",
      matching: 271,
      simpleLabel: "BANQUE POPULAIRE GRAND OUEST",
      siren: "857500227",
    },
    {
      activitePrincipale: "Agences immobilières",
      activitePrincipaleUniteLegale: "68.31Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5499",
      conventions: [
        {
          num: 1527,
          shortTitle:
            "Immobilier : administrateurs de biens, sociétés immobilières, agents immobiliers",
          id: "KALICONT000005635413",
          title:
            "Convention collective nationale de l'immobilier, administrateurs de biens, sociétés immobilières, agents immobiliers, etc. (anciennement cabinets d'administrateurs de biens et des sociétés immobilières), du 9 septembre 1988. Etendue par arrêté du 24 février 1989 JORF 3 mars 1989. Mise à jour par avenant  n° 47 du 23 novembre 2010, JORF 18 juillet 2012 ",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635413",
          slug: "1527-immobilier-administrateurs-de-biens-societes-immobilieres-agents-immobi",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1997-10-15",
      dateDebut: "2018-12-31",
      etablissements: 8,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "68.31Z",
        address: "1 BD DU SOUBEYRAN 48000 MENDE",
        categorieEntreprise: "PME",
        codeCommuneEtablissement: "48095",
        codePostalEtablissement: "48000",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["1527"],
        libelleCommuneEtablissement: "MENDE",
        siret: "41397622600089",
      },
      highlightLabel:
        "LE <b><u>CARREFOUR</u></b> DE L'IMMOBILIER ORPI LA LAUZE",
      label: "LE CARREFOUR DE L'IMMOBILIER ORPI LA LAUZE",
      matching: 3,
      simpleLabel: "LE CARREFOUR DE L'IMMOBILIER",
      siren: "413976226",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5599",
      conventions: [
        {
          num: 2120,
          shortTitle: "Banque",
          id: "KALICONT000005635780",
          title:
            "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
          slug: "2120-banque",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1954-01-01",
      dateDebut: "2022-05-06",
      etablissements: 472,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "5 RUE FRANKLIN ROOSEVELT 02190 VILLENEUVE-SUR-AISNE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "02360",
        codePostalEtablissement: "02190",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["2120"],
        libelleCommuneEtablissement: "VILLENEUVE-SUR-AISNE",
        siret: "75480071205292",
      },
      highlightLabel: "CIC EST <b><u>BANQUE</u></b>",
      label: "CIC EST BANQUE",
      matching: 247,
      simpleLabel: "BANQUE CIC EST",
      siren: "754800712",
    },
    {
      activitePrincipale: "Autres activités de soutien aux entreprises n.c.a.",
      activitePrincipaleUniteLegale: "82.99Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5710",
      conventions: [
        {
          num: 2216,
          shortTitle:
            "Commerce de détail et de gros à prédominance alimentaire",
          id: "KALICONT000005635085",
          title:
            "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
          slug: "2216-commerce-de-detail-et-de-gros-a-predominance-alimentaire",
          contributions: true,
        },
      ],
      dateCreationUniteLegale: "1992-03-26",
      dateDebut: "2018-10-01",
      etablissements: 8,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "82.99Z",
        address: "93 AV DE PARIS 91300 MASSY",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "91377",
        codePostalEtablissement: "91300",
        etablissementSiege: true,
        etatAdministratifEtablissement: "A",
        idccs: ["2216"],
        libelleCommuneEtablissement: "MASSY",
        siret: "38517158200088",
      },
      highlightLabel:
        "CMI <b><u>CARREFOUR</u></b> MARCHANDISES INTERNATIONALES",
      label: "CMI CARREFOUR MARCHANDISES INTERNATIONALES",
      matching: 1,
      simpleLabel: "CARREFOUR MARCHANDISES INTERNATIONALES",
      siren: "385171582",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5192",
      conventions: [
        {
          num: 3210,
          shortTitle: "Banque populaire",
          id: "KALICONT000031197865",
          title: "Convention collective Banque populaire  du 15 juin 2015",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000031197865",
          slug: "3210-banque-populaire",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1955-01-01",
      dateDebut: "2023-05-11",
      etablissements: 360,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "5 T BD CHANZY 16300 BARBEZIEUX-SAINT-HILAIRE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "16028",
        codePostalEtablissement: "16300",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["3210"],
        libelleCommuneEtablissement: "BARBEZIEUX-SAINT-HILAIRE",
        siret: "75550159000276",
      },
      highlightLabel:
        "BPACA <b><u>BANQUE</u></b> POPULAIRE AQUITAINE CENTRE ATLANTIQUE",
      label: "BPACA BANQUE POPULAIRE AQUITAINE CENTRE ATLANTIQUE",
      matching: 198,
      simpleLabel: "BANQUE POPULAIRE AQUITAINE CENTRE ATLANTIQUE",
      siren: "755501590",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5560",
      conventions: [
        {
          num: 3210,
          shortTitle: "Banque populaire",
          id: "KALICONT000031197865",
          title: "Convention collective Banque populaire  du 15 juin 2015",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000031197865",
          slug: "3210-banque-populaire",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1955-01-01",
      dateDebut: "2023-06-06",
      etablissements: 448,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "57 RUE DE LA REPUBLIQUE 01200 VALSERHONE",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "01033",
        codePostalEtablissement: "01200",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["3210"],
        libelleCommuneEtablissement: "VALSERHONE",
        siret: "60552007100818",
      },
      highlightLabel:
        "BP AURA <b><u>BANQUE</u></b> POPULAIRE AUVERGNE RHONE ALPES",
      label: "BP AURA BANQUE POPULAIRE AUVERGNE RHONE ALPES",
      matching: 303,
      simpleLabel: "BANQUE POPULAIRE AUVERGNE RHONE ALPES",
      siren: "605520071",
    },
    {
      activitePrincipale: "Autres intermédiations monétaires",
      activitePrincipaleUniteLegale: "64.19Z",
      allMatchingEtablissements: [],
      caractereEmployeurUniteLegale: "O",
      categorieJuridiqueUniteLegale: "5560",
      conventions: [
        {
          num: 3210,
          shortTitle: "Banque populaire",
          id: "KALICONT000031197865",
          title: "Convention collective Banque populaire  du 15 juin 2015",
          url: "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000031197865",
          slug: "3210-banque-populaire",
          contributions: false,
        },
      ],
      dateCreationUniteLegale: "1929-07-01",
      dateDebut: "2023-05-31",
      etablissements: 475,
      etatAdministratifUniteLegale: "A",
      firstMatchingEtablissement: {
        activitePrincipaleEtablissement: "64.19Z",
        address: "1 PL JEAN DE LA FONTAINE 02400 CHATEAU-THIERRY",
        categorieEntreprise: "GE",
        codeCommuneEtablissement: "02168",
        codePostalEtablissement: "02400",
        etablissementSiege: false,
        etatAdministratifEtablissement: "A",
        idccs: ["3210"],
        libelleCommuneEtablissement: "CHATEAU-THIERRY",
        siret: "55209179500732",
      },
      highlightLabel: "BRED <b><u>BANQUE</u></b> POPULAIRE",
      label: "BRED BANQUE POPULAIRE",
      matching: 313,
      simpleLabel: "BRED BANQUE POPULAIRE",
      siren: "552091795",
    },
  ],
};
