name: ♻️ Deactivate
on:
  pull_request:
    types: [closed]
  delete:
    branches:
      - "**"
      - "!v*"
      - "!master"
      - "!main"
      - "!dev"
      - "!develop"
      - "!**/persist"
      - "!persist/**"
      - "!**/persist/**"
      - "!persist-**"
      - "!**-persist"
      - "!**-persist-**"

jobs:
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-deactivate-atlas.yaml@v1
    secrets: inherit
