name: End-to-end testing

on:
  repository_dispatch:
    types: [deployment-ended]

concurrency:
  cancel-in-progress: true
  group: e2e-${{ github.ref }}

jobs:
  e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile
      - name: Run test e2e
        run: |
          CODECEPT_BASEURL=https://${{ github.event.client_payload.url }} yarn test:e2e
