name: Tests e2e (heavy + light)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  e2e:
    name: End-to-end testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Run test e2e
        run: |
          TEST_BASEURL=https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr ALL_TEST=true yarn test:e2e
      - name: Archive generated screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-screenshots
          path: |
            packages/code-du-travail-frontend/cypress/screenshots
      - name: Create the Mattermost Message
        if: failure()
        run: |
          echo "{\"text\":\"Les tests automatiques e2e ont échoué sur la pré-prod. Reportez-vous à ce run : ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} (cc: @max @victorz @carolinebda @martial)\"}" > mattermost.json
      - name: Send message to mattermost if failure
        uses: mattermost/action-mattermost-notify@master
        if: failure()
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
