name: End-to-end testing

on:
  workflow_run:
    workflows: ["Review"]
    types:
      - completed

concurrency:
  cancel-in-progress: true
  group: e2e-${{ github.ref }}

jobs:
  e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile
      - name: Download k8s manifests
        uses: actions/download-artifact@v2
        with:
          name: manifests-dev.yml
      - name: Get deployment url
        uses: mikefarah/yq@v4.13.4
        id: url
        with:
          cmd: echo $(cat manifests-dev.yml | yq eval-all '.spec.rules[] .host' - | tail -n 1)
      - name: Run test e2e
        run: |
          CODECEPT_BASEURL=https://${{ steps.url.outputs.result }} yarn test:e2e
