name: 😎 PreProd
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  socialgouv:
    name: "🇫🇷 SocialGouv"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-preproduction.yaml@v1
    secrets: inherit
  e2e:
    name: End-to-end testing
    runs-on: ubuntu-latest
    needs: [socialgouv]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Run test e2e
        run: |
          TEST_BASEURL=https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr ALL_TEST=true yarn test:e2e
      - name: Archive generated screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-screenshots
          path: |
            packages/code-du-travail-frontend/cypress/screenshots
