name: Pre-production

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  group: pre-production
  cancel-in-progress: true

jobs:
  register-frontend:
    name: Register frontend
    runs-on: ubuntu-latest
    steps:
      - name: Get commit sha
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          environment: preprod
          project: "cdtn"
          imageName: "cdtn/code-du-travail-frontend"
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./Dockerfile"
          dockercontext: "."
          dockerbuildargs: |
            NEXT_PUBLIC_SENTRY_DSN=https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
            NEXT_PUBLIC_SENTRY_ENV=preproduction
            NEXT_PUBLIC_SENTRY_ORG=incubateur
            NEXT_PUBLIC_SENTRY_PROJECT=code-du-travail-numerique
            NEXT_PUBLIC_AZURE_BASE_URL=https://cdtnadmindev.blob.core.windows.net
            NEXT_PUBLIC_AZURE_CONTAINER=cdtn
            NEXT_PUBLIC_PIWIK_SITE_ID=3
            NEXT_PUBLIC_PIWIK_URL=https://matomo.fabrique.social.gouv.fr
            NEXT_PUBLIC_COMMIT=${{ env.GITHUB_SHA }}
            NEXT_PUBLIC_SITE_URL=https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr
            NEXT_PUBLIC_IS_PREPRODUCTION_DEPLOYMENT=true
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG=incubateur
            SENTRY_PROJECT=code-du-travail-numerique

  manifests:
    name: Preproduction manifests
    runs-on: ubuntu-latest
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "preprod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          ELASTIC_APM_ENVIRONMENT: cdtn-preprod
          ES_INDEX_PREFIX: cdtn-preprod

  deploy-preprod:
    name: Deploy preproduction
    runs-on: ubuntu-latest
    needs: [register-frontend, manifests]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "preprod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
