name: Preproduction

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  group: pre-production
  cancel-in-progress: true

jobs:
  register:
    name: Register images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - images: "code-du-travail-frontend"
            path: "."
            args: |
              NEXT_PUBLIC_SENTRY_DSN=https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
              NEXT_PUBLIC_SENTRY_ENV=production
          - images: "code-du-travail-api"
            path: "./packages/code-du-travail-api/"
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          environment: preprod
          project: "cdtn"
          imageName: cdtn/${{ matrix.images }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.path }}/Dockerfile"
          dockercontext: "${{ matrix.path }}"
          dockerbuildargs: ${{ matrix.args }}

  manifests:
    name: Preproduction manifests
    runs-on: ubuntu-latest
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "preprod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          ELASTIC_APM_ENVIRONMENT: cdtn-preprod
          ES_INDEX_PREFIX: cdtn-preprod

  deploy-preprod:
    name: Deploy preproduction
    runs-on: ubuntu-latest
    needs: [register, manifests]
    environment:
      name: preproduction
      url: https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "preprod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
