name: 😎 PreProd
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  build-app:
    environment: build-preproduction
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout code repository
        uses: actions/checkout@v4

      - name: 📌 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY_URL }}/${{ vars.PROJECT_NAME }}/${{ github.event.repository.name }}/app
          tags: |
            type=sha,prefix=preprod-,format=long,priority=850
            type=sha,prefix=sha-,format=long,priority=890

      - name: 📦 Build and push Docker image for app
        uses: socialgouv/workflows/actions/buildkit@v1
        with:
          context: "."
          dockerfile: "Dockerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          registry: "${{ vars.REGISTRY_URL }}"
          registry-username: "${{ secrets.REGISTRY_USERNAME }}"
          registry-password: "${{ secrets.REGISTRY_PASSWORD }}"
          buildkit-cert-ca: "${{ secrets.BUILDKIT_CERT_CA }}"
          buildkit-cert: "${{ secrets.BUILDKIT_CERT }}"
          buildkit-cert-key: "${{ secrets.BUILDKIT_CERT_KEY }}"
          buildkit-svc-count: ${{ vars.BUILDKIT_SVC_COUNT }}
          buildkit-daemon-address: ${{ vars.BUILDKIT_DAEMON_ADDRESS }}
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            ELASTICSEARCH_TOKEN_API=${{ secrets.ELASTICSEARCH_TOKEN_API }}
            ELASTICSEARCH_URL=${{ secrets.ELASTICSEARCH_URL }}
          build-args: |
            NEXT_PUBLIC_CDTN_ENV=preproduction
            NEXT_PUBLIC_IS_PREPRODUCTION_DEPLOYMENT=true
            NEXT_PUBLIC_BUCKET_FOLDER=preview
            NEXT_PUBLIC_BUCKET_SITEMAP_FOLDER=sitemap
            NEXT_PUBLIC_BUCKET_URL=https://cdtn-prod-public.s3.gra.io.cloud.ovh.net
            NEXT_PUBLIC_PIWIK_SITE_ID=3
            NEXT_PUBLIC_PIWIK_URL=https://matomo.fabrique.social.gouv.fr
            NEXT_PUBLIC_COMMIT=${{ github.sha }}
            NEXT_PUBLIC_SITE_URL=https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.PUBLIC_SENTRY_DSN }}
            NEXT_PUBLIC_SENTRY_ENV=preproduction
            NEXT_PUBLIC_ES_INDEX_PREFIX=cdtn-preprod
            SENTRY_RELEASE=${{ github.sha }}
            SENTRY_ORG=incubateur
            SENTRY_PROJECT=fabnum-code-du-travail-numerique
            SENTRY_URL=https://sentry2.fabrique.social.gouv.fr

  kontinuous:
    needs: [build-app]
    name: "Deploy on Kubernetes 🐳"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-preproduction-atlas.yaml@v1
    secrets: inherit
  e2e:
    name: End-to-end testing
    runs-on: ubuntu-latest
    needs: [kontinuous]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Run test e2e
        run: |
          TEST_BASEURL=https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr TEST_MODE=heavy-and-light yarn test:e2e
      - name: Archive generated screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: |
            packages/code-du-travail-frontend/cypress/screenshots
