name: Pre-production

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  group: pre-production
  cancel-in-progress: true

jobs:
  register-frontend:
    name: Register frontend
    runs-on: ubuntu-latest
    steps:
      - name: Get branch slug and commit sha
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
          echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          environment: preprod
          project: "cdtn"
          imageName: "cdtn/code-du-travail-frontend"
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./Dockerfile"
          dockercontext: "."
          dockerbuildargs: |
              NEXT_PUBLIC_SENTRY_DSN=https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
              NEXT_PUBLIC_SENTRY_ENV=preproduction
              NEXT_PUBLIC_AZURE_BASE_URL=https://cdtnadmindev.blob.core.windows.net
              NEXT_PUBLIC_AZURE_CONTAINER=cdtn
              NEXT_PUBLIC_PIWIK_SITE_ID=3
              NEXT_PUBLIC_PIWIK_URL=https://matomo.fabrique.social.gouv.fr
              NEXT_PUBLIC_API_ENTREPRISE_URL=https://entreprise.data.gouv.fr/api/sirene
              NEXT_PUBLIC_API_SIRET2IDCC_URL=https://siret2idcc.fabrique.social.gouv.fr/api/v2
              NEXT_PUBLIC_API_URL=https://api-code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/api/v1
              NEXT_PUBLIC_COMMIT=${{ env.GITHUB_SHA }}

  register-api:
    name: Register api
    runs-on: ubuntu-latest
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          environment: preprod
          project: "cdtn"
          imageName: "cdtn/code-du-travail-api"
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./packages/code-du-travail-api/Dockerfile"
          dockercontext: "./packages/code-du-travail-api"

  manifests:
    name: Preproduction manifests
    runs-on: ubuntu-latest
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "preprod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          ELASTIC_APM_ENVIRONMENT: cdtn-preprod
          ES_INDEX_PREFIX: cdtn-preprod

  deploy-preprod:
    name: Deploy preproduction
    runs-on: ubuntu-latest
    needs: [register-frontend, register-api, manifests]
    environment:
      name: preproduction
      url: https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "preprod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
