name: Production

on:
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  register:
    name: Build & Register images
    runs-on: ubuntu-latest
    steps:
      - name: Register docker image for api
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: "cdtn"
          imageName: cdtn/code-du-travail-api
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./packages/code-du-travail-api/Dockerfile"
          dockercontext: "./packages/code-du-travail-api"
      - name: Register docker image for frontend
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: "cdtn"
          imageName: cdtn/code-du-travail-frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./Dockerfile"
          dockercontext: "./"

  manifests:
    name: Preproduction manifests
    runs-on: ubuntu-latest
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "prod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvbaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          ES_INDEX_PREFIX: cdtn-prod

  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://code.travail.gouv.fr/
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "prod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          KUBE_NAMESPACE: "cdtn"

      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
