name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  register-frontend:
    name: Register frontend
    runs-on: ubuntu-latest
    steps:
      - name: Get commit sha
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          environment: prod
          project: "cdtn"
          imageName: "cdtn/code-du-travail-frontend"
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./Dockerfile"
          dockercontext: "."
          dockerbuildargs: |
            NEXT_PUBLIC_SENTRY_DSN=https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
            NEXT_PUBLIC_SENTRY_ENV=production
            NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT=true
            NEXT_PUBLIC_AZURE_BASE_URL=https://cdtnadminprod.blob.core.windows.net
            NEXT_PUBLIC_AZURE_CONTAINER=cdtn
            NEXT_PUBLIC_PIWIK_SITE_ID=4
            NEXT_PUBLIC_PIWIK_URL=https://matomo.fabrique.social.gouv.fr
            NEXT_PUBLIC_COMMIT=${{ env.GITHUB_SHA }}
            NEXT_PUBLIC_SITE_URL=https://code.travail.gouv.fr

  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register-frontend]
    steps:
      - name: Use autodevops manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "prod"
          productionNamespace: "cdtn"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          ELASTIC_APM_ENVIRONMENT: cdtn-prod
          ES_INDEX_PREFIX: cdtn-prod
          KUBE_NAMESPACE: cdtn

      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
