name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  branch-info:
    name: Get branch slug and commit sha
    runs-on: ubuntu-latest
    steps:
      - name: Get branch slug and commit sha
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
          echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

  register:
    name: Register images
    runs-on: ubuntu-latest
    needs: [ branch-info ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - images: "code-du-travail-frontend"
            path: "."
            args: |
              NEXT_PUBLIC_SENTRY_DSN=https://c2aa7e731a494cfd8f7fb1ddabca11c9@sentry.fabrique.social.gouv.fr/5
              NEXT_PUBLIC_SENTRY_ENV=production
              NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT=true
              NEXT_PUBLIC_AZURE_BASE_URL=https://cdtnadminprod.blob.core.windows.net
              NEXT_PUBLIC_AZURE_CONTAINER=cdtn
              NEXT_PUBLIC_PIWIK_SITE_ID=4
              NEXT_PUBLIC_PIWIK_URL=https://matomo.fabrique.social.gouv.fr
              NEXT_PUBLIC_API_ENTREPRISE_URL=https://entreprise.data.gouv.fr/api/sirene
              NEXT_PUBLIC_API_SIRET2IDCC_URL=https://siret2idcc.fabrique.social.gouv.fr/api/v2
              NEXT_PUBLIC_API_URL=https://api.cdtn.fabrique.social.gouv.fr/api/v1
              NEXT_PUBLIC_COMMIT=${{ env.GITHUB_SHA }}
          - images: "code-du-travail-api"
            path: "./packages/code-du-travail-api/"
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          environment: prod
          project: "cdtn"
          imageName: cdtn/${{ matrix.images }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.path }}/Dockerfile"
          dockercontext: "${{ matrix.path }}"
          dockerbuildargs: ${{ matrix.args }}

  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: production
      url: https://code.travail.gouv.fr/
    steps:
      - name: Use autodevops manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "prod"
          productionNamespace: "cdtn"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        env:
          ELASTIC_APM_ENVIRONMENT: cdtn-prod
          ES_INDEX_PREFIX: cdtn-prod
          KUBE_NAMESPACE: cdtn

      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
