name: Code quality

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - dev

concurrency:
  cancel-in-progress: true
  group: quality-${{ github.ref }}

jobs:
  register-elastic:
    name: Register elasticsearch
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          project: "cdtn"
          imageName: cdtn/elasticsearch
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./docker/elasticsearch/Dockerfile"
          dockercontext: "./docker/elasticsearch"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile
      - name: Build code
        run: |
          yarn build
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        repositories:
          [
            "@socialgouv/cdtn-ui",
            "@socialgouv/react-fiche-service-public",
            "@cdt/frontend",
            "@cdt/data",
            "@socialgouv/modeles-social",
            "@cdt/api",
          ]
    steps:
      - uses: actions/cache@v3
        name: Restore build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Lint ${{ matrix.repositories }}
        run: |
          yarn workspace ${{ matrix.repositories }} lint

  type-check:
    name: Check typescript types
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        repositories:
          [
            "@cdt/frontend",
            "@cdt/data",
            "@socialgouv/modeles-social",
            "@cdt/api",
          ]
    steps:
      - uses: actions/cache@v3
        name: Restore build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Lint ${{ matrix.repositories }}
        run: |
          yarn workspace ${{ matrix.repositories }} type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [register-elastic, build]
    services:
      elasticsearch:
        image: ghcr.io/socialgouv/cdtn/elasticsearch:sha-${{ github.sha }}
        ports:
          - 9200:9200
        env:
          ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        options: >-
          --health-cmd "curl -sS http://localhost:9200/_cat/health?h=status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6
    strategy:
      fail-fast: false
      matrix:
        repositories:
          [
            "@socialgouv/cdtn-ui",
            "@socialgouv/react-fiche-service-public",
            "@cdt/frontend",
            "@cdt/data",
            "@socialgouv/modeles-social",
            "@cdt/api",
          ]
    steps:
      - uses: actions/cache@v3
        name: Restore build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Test ${{ matrix.repositories }}
        run: |
          yarn workspace ${{ matrix.repositories }} test
        env:
          ELASTICSEARCH_URL: http://localhost:9200

  docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          recursive: true
