name: Code quality

on: [push]

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: ghcr.io/socialgouv/cdtn/elasticsearch:sha-${{ github.sha }}
        ports:
          - 9200:9200
        env:
          ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        options: >-
          --health-cmd "curl -sS http://localhost:9200/_cat/health?h=status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Lint socialgouv/cdtn-ui
        run: |
          yarn workspace @socialgouv/cdtn-ui lint
      - name: Test @socialgouv/cdtn-ui
        run: |
          yarn workspace @socialgouv/cdtn-ui test
      - name: Lint @socialgouv/react-fiche-service-public
        run: |
          yarn workspace @socialgouv/react-fiche-service-public lint
      - name: Test @socialgouv/react-fiche-service-public
        run: |
          yarn workspace @socialgouv/react-fiche-service-public test
      - name: Lint @cdt/frontend
        run: |
          yarn workspace @cdt/frontend lint
      - name: Test @cdt/frontend
        run: |
          yarn workspace @cdt/frontend test
      - name: Lint @cdt/data
        run: |
          yarn workspace @cdt/data lint
      - name: Test @cdt/data
        run: |
          yarn workspace @cdt/data test
      - name: Lint @socialgouv/modeles-social
        run: |
          yarn workspace @socialgouv/modeles-social lint
      - name: Test @socialgouv/modeles-social
        run: |
          yarn workspace @socialgouv/modeles-social test
      - name: Lint @cdt/api
        run: |
          yarn workspace @cdt/api lint
      - name: Test @cdt/api
        env:
          ELASTICSEARCH_URL: http://localhost:9200
        run: |
          yarn workspace @cdt/api test --coverage

  docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          recursive: true

  services-de-renseignement:
    name: Get url from service de renseignement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test SDR urls
        run: |
          jq ".[].url" ./packages/code-du-travail-frontend/src/data/services-de-renseignement.json | xargs -n 1 wget  --spider
