name: Code quality

on: [pull_request]

concurrency:
  cancel-in-progress: true
  group: quality-${{ github.ref }}

jobs:
  register-elastic:
    name: Register elasticsearch
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          project: "cdtn"
          imageName: cdtn/elasticsearch
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./docker/elasticsearch/Dockerfile"
          dockercontext: "./docker/elasticsearch"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repositories:
          [
            "@socialgouv/cdtn-ui",
            "@socialgouv/react-fiche-service-public",
            "@cdt/frontend",
            "@cdt/data",
            "@socialgouv/modeles-social",
            "@cdt/api",
          ]
    steps:
      - name: Lint ${{ matrix.repositories }}
        run: |
          yarn workspace ${{ matrix.repositories }} lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [register-elastic]
    services:
      elasticsearch:
        image: ghcr.io/socialgouv/cdtn/elasticsearch:sha-${{ github.sha }}
        ports:
          - 9200:9200
        env:
          ES_JAVA_OPTS: "-Xms256m -Xmx256m"
        options: >-
          --health-cmd "curl -sS http://localhost:9200/_cat/health?h=status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6
    strategy:
      fail-fast: false
      matrix:
        repositories:
          [
            "@socialgouv/cdtn-ui",
            "@socialgouv/react-fiche-service-public",
            "@cdt/frontend",
            "@cdt/data",
            "@socialgouv/modeles-social",
            "@cdt/api",
          ]
    steps:
      - name: Test ${{ matrix.repositories }}
        run: |
          yarn workspace ${{ matrix.repositories }} test
        env:
          ELASTICSEARCH_URL: http://localhost:9200

  docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          recursive: true
