name: Registration

on:
  - push

jobs:
  register-elastic:
    name: Register elasticsearch
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: "cdtn"
          imageName: cdtn/elasticsearch
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./docker/elasticsearch/Dockerfile"
          dockercontext: "./docker/elasticsearch"
