name: Storybook

on:
  push:
    branches: ["dev"]

concurrency:
  cancel-in-progress: true
  group: storybook-${{ github.ref }}

jobs:
  storybook:
    name: Deployment storybook on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn storybook:deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
