name: Trivy vulnerability scanner
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*

jobs:
  register-api:
    name: Register api
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: "cdtn"
          imageName: cdtn/code-du-travail-api
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./packages/code-du-travail-api/Dockerfile"
          dockercontext: "./packages/code-du-travail-api"

  register-frontend:
    name: Register frontend
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: "cdtn"
          imageName: cdtn/code-du-travail-frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./packages/code-du-travail-frontend/Dockerfile"
          dockercontext: "./packages/code-du-travail-frontend"

  trivy:
    name: Run trivy
    runs-on: ubuntu-18.04
    needs: [register-api, register-frontend]
    strategy:
      fail-fast: false
      matrix:
        images: ["code-du-travail-frontend", "code-du-travail-api"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ${{ matrix.images }} from Dockerfile
        run: |
          docker build -t ghcr.io/socialgouv/cdtn/${{ matrix.images }}:sha-${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/socialgouv/cdtn/${{ matrix.images }}:sha-${{ github.sha }}"
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
