import {
  ReferenceSalaryFactory,
  SupportedCcIndemniteLicenciement,
} from "../../../../common";

describe("Calcul du salaire pour la CC 675", () => {
  const factory = new ReferenceSalaryFactory();
  const sref = factory.create(SupportedCcIndemniteLicenciement.IDCC0675);

  test.each`
    salaries                                                                                                                                                                                                                                                                                                                                                                                                                                  | isAgentMaitriseOrCadre | expectedResult
    ${[]}                                                                                                                                                                                                                                                                                                                                                                                                                                     | ${false}               | ${0}
    ${[{ month: "janvier", value: 2000 }, { month: "février", value: 3000 }]}                                                                                                                                                                                                                                                                                                                                                                 | ${false}               | ${1666.6666666666667}
    ${[{ month: "janvier", value: 2000 }, { month: "février", value: 3000 }, { month: "mars", value: 4000 }]}                                                                                                                                                                                                                                                                                                                                 | ${false}               | ${3000}
    ${[{ month: "janvier", value: 2000 }, { month: "février", value: 3000 }, { month: "mars", value: 4000 }, { month: "avril", value: 1000000 }]}                                                                                                                                                                                                                                                                                             | ${false}               | ${335666.6666666667}
    ${[{ month: "janvier", value: 2500 }, { month: "février", value: 2200 }, { month: "mars", value: 2200 }, { month: "avril", value: 2200 }]}                                                                                                                                                                                                                                                                                                | ${false}               | ${2200}
    ${[{ month: "avril", value: 2200 }, { month: "février", value: 2200 }, { month: "mars", value: 2200 }, { month: "janvier", value: 2500 }]}                                                                                                                                                                                                                                                                                                | ${false}               | ${2200}
    ${[{ month: "janvier", value: 2493 }, { month: "février", value: 2631 }, { month: "mars", value: 2502 }, { month: "avril", value: 2683 }, { month: "mai", value: 2718 }, { month: "juin", value: 2778 }, { month: "juillet", value: 2534 }, { month: "aout", value: 2710 }, { month: "septembre", value: 2778 }, { month: "octobre", value: 2467 }, { month: "novembre", value: 2685 }, { month: "décembre", value: 2719 }]}              | ${false}               | ${2641.5}
    ${[{ month: "janvier", prime: 1200, value: 2493 }, { month: "février", value: 2631 }, { month: "mars", value: 2502 }, { month: "avril", value: 2683 }, { month: "mai", value: 2718 }, { month: "juin", value: 2778 }, { month: "juillet", value: 2534 }, { month: "aout", value: 2710 }, { month: "septembre", value: 2778 }, { month: "octobre", value: 2467 }, { month: "novembre", value: 2685 }, { month: "décembre", value: 2719 }]} | ${false}               | ${2641.5}
    ${[{ month: "janvier", value: 2493 }, { month: "février", value: 2631 }, { month: "mars", value: 2502 }, { month: "avril", value: 2683 }, { month: "mai", value: 2718 }, { month: "juin", value: 2778 }, { month: "juillet", value: 2534 }, { month: "aout", value: 2710 }, { month: "septembre", value: 2778 }, { month: "octobre", value: 2467 }, { month: "novembre", value: 2685 }, { month: "décembre", prime: 1200, value: 2719 }]} | ${false}               | ${2641.5}
    ${[]}                                                                                                                                                                                                                                                                                                                                                                                                                                     | ${true}                | ${0}
    ${[{ month: "janvier", value: 2000 }, { month: "février", value: 3000 }]}                                                                                                                                                                                                                                                                                                                                                                 | ${true}                | ${416.6666666666667}
    ${[{ month: "janvier", value: 2000 }, { month: "février", value: 3000 }, { month: "mars", value: 4000 }]}                                                                                                                                                                                                                                                                                                                                 | ${true}                | ${750}
    ${[{ month: "janvier", value: 2000 }, { month: "février", value: 3000 }, { month: "mars", value: 4000 }, { month: "avril", value: 1000000 }]}                                                                                                                                                                                                                                                                                             | ${true}                | ${84083.33333333333}
    ${[{ month: "janvier", value: 2500 }, { month: "février", value: 2200 }, { month: "mars", value: 2200 }, { month: "avril", value: 2200 }]}                                                                                                                                                                                                                                                                                                | ${true}                | ${758.3333333333334}
    ${[{ month: "avril", value: 2200 }, { month: "février", value: 2200 }, { month: "mars", value: 2200 }, { month: "janvier", value: 2500 }]}                                                                                                                                                                                                                                                                                                | ${true}                | ${758.3333333333334}
    ${[{ month: "janvier", value: 2493 }, { month: "février", value: 2631 }, { month: "mars", value: 2502 }, { month: "avril", value: 2683 }, { month: "mai", value: 2718 }, { month: "juin", value: 2778 }, { month: "juillet", value: 2534 }, { month: "aout", value: 2710 }, { month: "septembre", value: 2778 }, { month: "octobre", value: 2467 }, { month: "novembre", value: 2685 }, { month: "décembre", value: 2719 }]}              | ${true}                | ${2641.5}
    ${[{ month: "janvier", prime: 1200, value: 2493 }, { month: "février", value: 2631 }, { month: "mars", value: 2502 }, { month: "avril", value: 2683 }, { month: "mai", value: 2718 }, { month: "juin", value: 2778 }, { month: "juillet", value: 2534 }, { month: "aout", value: 2710 }, { month: "septembre", value: 2778 }, { month: "octobre", value: 2467 }, { month: "novembre", value: 2685 }, { month: "décembre", value: 2719 }]} | ${true}                | ${2641.5}
    ${[{ month: "janvier", value: 2493 }, { month: "février", value: 2631 }, { month: "mars", value: 2502 }, { month: "avril", value: 2683 }, { month: "mai", value: 2718 }, { month: "juin", value: 2778 }, { month: "juillet", value: 2534 }, { month: "aout", value: 2710 }, { month: "septembre", value: 2778 }, { month: "octobre", value: 2467 }, { month: "novembre", value: 2685 }, { month: "décembre", prime: 1200, value: 2719 }]} | ${true}                | ${2641.5}
  `(
    "Salaires : $salaries => $expectedResult €",
    ({ salaries, isAgentMaitriseOrCadre, expectedResult }) => {
      expect(
        sref.computeReferenceSalary({
          isAgentMaitriseOrCadre,
          salaires: salaries,
        })
      ).toEqual(expectedResult);
    }
  );
});
